// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/providers/analytics_provider_session_ownership_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:go_hard_app/data/models/workout_stats.dart' as _i2;
import 'package:go_hard_app/data/repositories/analytics_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkoutStats_0 extends _i1.SmartFake implements _i2.WorkoutStats {
  _FakeWorkoutStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AnalyticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsRepository extends _i1.Mock
    implements _i3.AnalyticsRepository {
  MockAnalyticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set afterLocalReadForTesting(
    _i4.Future<void> Function()? _afterLocalReadForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#afterLocalReadForTesting, _afterLocalReadForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set beforeReturnForTesting(
    _i4.Future<void> Function()? _beforeReturnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeReturnForTesting, _beforeReturnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.WorkoutStats> getWorkoutStats() =>
      (super.noSuchMethod(
            Invocation.method(#getWorkoutStats, []),
            returnValue: _i4.Future<_i2.WorkoutStats>.value(
              _FakeWorkoutStats_0(
                this,
                Invocation.method(#getWorkoutStats, []),
              ),
            ),
          )
          as _i4.Future<_i2.WorkoutStats>);

  @override
  _i4.Future<List<_i2.ExerciseProgress>> getExerciseProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseProgress, []),
            returnValue: _i4.Future<List<_i2.ExerciseProgress>>.value(
              <_i2.ExerciseProgress>[],
            ),
          )
          as _i4.Future<List<_i2.ExerciseProgress>>);

  @override
  _i4.Future<List<_i2.ProgressDataPoint>> getExerciseProgressOverTime(
    int? exerciseTemplateId, {
    int? days = 90,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getExerciseProgressOverTime,
              [exerciseTemplateId],
              {#days: days},
            ),
            returnValue: _i4.Future<List<_i2.ProgressDataPoint>>.value(
              <_i2.ProgressDataPoint>[],
            ),
          )
          as _i4.Future<List<_i2.ProgressDataPoint>>);

  @override
  _i4.Future<List<_i2.MuscleGroupVolume>> getMuscleGroupVolume({
    int? days = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMuscleGroupVolume, [], {#days: days}),
            returnValue: _i4.Future<List<_i2.MuscleGroupVolume>>.value(
              <_i2.MuscleGroupVolume>[],
            ),
          )
          as _i4.Future<List<_i2.MuscleGroupVolume>>);

  @override
  _i4.Future<List<_i2.PersonalRecord>> getPersonalRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getPersonalRecords, []),
            returnValue: _i4.Future<List<_i2.PersonalRecord>>.value(
              <_i2.PersonalRecord>[],
            ),
          )
          as _i4.Future<List<_i2.PersonalRecord>>);

  @override
  _i4.Future<List<_i2.ProgressDataPoint>> getVolumeOverTime({int? days = 90}) =>
      (super.noSuchMethod(
            Invocation.method(#getVolumeOverTime, [], {#days: days}),
            returnValue: _i4.Future<List<_i2.ProgressDataPoint>>.value(
              <_i2.ProgressDataPoint>[],
            ),
          )
          as _i4.Future<List<_i2.ProgressDataPoint>>);
}
