// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/providers/chat_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i7;

import 'package:go_hard_app/core/services/connectivity_service.dart' as _i6;
import 'package:go_hard_app/data/models/chat_conversation.dart' as _i4;
import 'package:go_hard_app/data/models/chat_message.dart' as _i5;
import 'package:go_hard_app/data/repositories/chat_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMealPlanPreview_0 extends _i1.SmartFake
    implements _i2.MealPlanPreview {
  _FakeMealPlanPreview_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApplyMealPlanResult_1 extends _i1.SmartFake
    implements _i2.ApplyMealPlanResult {
  _FakeApplyMealPlanResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApplyMealPlanWeekResult_2 extends _i1.SmartFake
    implements _i2.ApplyMealPlanWeekResult {
  _FakeApplyMealPlanWeekResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i2.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ChatConversation>> getConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, []),
            returnValue: _i3.Future<List<_i4.ChatConversation>>.value(
              <_i4.ChatConversation>[],
            ),
          )
          as _i3.Future<List<_i4.ChatConversation>>);

  @override
  _i3.Future<_i4.ChatConversation?> getConversation(int? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversation, [conversationId]),
            returnValue: _i3.Future<_i4.ChatConversation?>.value(),
          )
          as _i3.Future<_i4.ChatConversation?>);

  @override
  _i3.Future<_i4.ChatConversation?> createConversation({
    required String? title,
    required String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [], {
              #title: title,
              #type: type,
            }),
            returnValue: _i3.Future<_i4.ChatConversation?>.value(),
          )
          as _i3.Future<_i4.ChatConversation?>);

  @override
  _i3.Future<_i5.ChatMessage?> sendMessage({
    required int? conversationId,
    required String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #conversationId: conversationId,
              #message: message,
            }),
            returnValue: _i3.Future<_i5.ChatMessage?>.value(),
          )
          as _i3.Future<_i5.ChatMessage?>);

  @override
  _i3.Future<bool> deleteConversation(int? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [conversationId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.ChatConversation?> generateWorkoutPlan({
    required String? goal,
    required String? experienceLevel,
    required int? daysPerWeek,
    required String? equipment,
    String? limitations,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateWorkoutPlan, [], {
              #goal: goal,
              #experienceLevel: experienceLevel,
              #daysPerWeek: daysPerWeek,
              #equipment: equipment,
              #limitations: limitations,
            }),
            returnValue: _i3.Future<_i4.ChatConversation?>.value(),
          )
          as _i3.Future<_i4.ChatConversation?>);

  @override
  _i3.Future<_i4.ChatConversation?> generateMealPlan({
    required String? dietaryGoal,
    int? targetCalories,
    String? macros,
    String? restrictions,
    String? preferences,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateMealPlan, [], {
              #dietaryGoal: dietaryGoal,
              #targetCalories: targetCalories,
              #macros: macros,
              #restrictions: restrictions,
              #preferences: preferences,
            }),
            returnValue: _i3.Future<_i4.ChatConversation?>.value(),
          )
          as _i3.Future<_i4.ChatConversation?>);

  @override
  _i3.Future<_i4.ChatConversation?> analyzeProgress({
    DateTime? startDate,
    DateTime? endDate,
    String? focusArea,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeProgress, [], {
              #startDate: startDate,
              #endDate: endDate,
              #focusArea: focusArea,
            }),
            returnValue: _i3.Future<_i4.ChatConversation?>.value(),
          )
          as _i3.Future<_i4.ChatConversation?>);

  @override
  _i3.Future<_i2.MealPlanPreview> previewMealPlan(int? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#previewMealPlan, [conversationId]),
            returnValue: _i3.Future<_i2.MealPlanPreview>.value(
              _FakeMealPlanPreview_0(
                this,
                Invocation.method(#previewMealPlan, [conversationId]),
              ),
            ),
          )
          as _i3.Future<_i2.MealPlanPreview>);

  @override
  _i3.Future<_i2.ApplyMealPlanResult> applyMealPlanToToday(
    int? conversationId, {
    int? day = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #applyMealPlanToToday,
              [conversationId],
              {#day: day},
            ),
            returnValue: _i3.Future<_i2.ApplyMealPlanResult>.value(
              _FakeApplyMealPlanResult_1(
                this,
                Invocation.method(
                  #applyMealPlanToToday,
                  [conversationId],
                  {#day: day},
                ),
              ),
            ),
          )
          as _i3.Future<_i2.ApplyMealPlanResult>);

  @override
  _i3.Future<_i2.ApplyMealPlanWeekResult> applyMealPlanWeek(
    int? conversationId, {
    bool? applyAllDays = false,
    List<int>? days,
    DateTime? startDate,
    bool? overwriteExisting = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #applyMealPlanWeek,
              [conversationId],
              {
                #applyAllDays: applyAllDays,
                #days: days,
                #startDate: startDate,
                #overwriteExisting: overwriteExisting,
              },
            ),
            returnValue: _i3.Future<_i2.ApplyMealPlanWeekResult>.value(
              _FakeApplyMealPlanWeekResult_2(
                this,
                Invocation.method(
                  #applyMealPlanWeek,
                  [conversationId],
                  {
                    #applyAllDays: applyAllDays,
                    #days: days,
                    #startDate: startDate,
                    #overwriteExisting: overwriteExisting,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i2.ApplyMealPlanWeekResult>);

  @override
  _i3.Future<Map<String, dynamic>> previewSessionsFromPlan({
    required int? conversationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#previewSessionsFromPlan, [], {
              #conversationId: conversationId,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> createSessionsFromPlan({
    required int? conversationId,
    DateTime? startDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSessionsFromPlan, [], {
              #conversationId: conversationId,
              #startDate: startDate,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> createProgramFromPlan({
    required int? conversationId,
    String? title,
    String? description,
    int? goalId,
    int? totalWeeks,
    int? daysPerWeek,
    DateTime? startDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProgramFromPlan, [], {
              #conversationId: conversationId,
              #title: title,
              #description: description,
              #goalId: goalId,
              #totalWeeks: totalWeeks,
              #daysPerWeek: daysPerWeek,
              #startDate: startDate,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i6.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  _i3.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> waitForConnection({
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForConnection, [], {#timeout: timeout}),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
