// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/providers/friends_provider_session_ownership_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:go_hard_app/data/models/friend.dart' as _i6;
import 'package:go_hard_app/data/models/friend_request.dart' as _i7;
import 'package:go_hard_app/data/models/friendship_status.dart' as _i2;
import 'package:go_hard_app/data/models/public_profile.dart' as _i3;
import 'package:go_hard_app/data/models/user_search_result.dart' as _i8;
import 'package:go_hard_app/data/repositories/friends_repository.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFriendshipStatus_0 extends _i1.SmartFake
    implements _i2.FriendshipStatus {
  _FakeFriendshipStatus_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePublicProfile_1 extends _i1.SmartFake implements _i3.PublicProfile {
  _FakePublicProfile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FriendsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendsRepository extends _i1.Mock implements _i4.FriendsRepository {
  MockFriendsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.Friend>> getFriends() =>
      (super.noSuchMethod(
            Invocation.method(#getFriends, []),
            returnValue: _i5.Future<List<_i6.Friend>>.value(<_i6.Friend>[]),
          )
          as _i5.Future<List<_i6.Friend>>);

  @override
  _i5.Future<List<_i7.FriendRequest>> getIncomingRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getIncomingRequests, []),
            returnValue: _i5.Future<List<_i7.FriendRequest>>.value(
              <_i7.FriendRequest>[],
            ),
          )
          as _i5.Future<List<_i7.FriendRequest>>);

  @override
  _i5.Future<List<_i7.FriendRequest>> getOutgoingRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getOutgoingRequests, []),
            returnValue: _i5.Future<List<_i7.FriendRequest>>.value(
              <_i7.FriendRequest>[],
            ),
          )
          as _i5.Future<List<_i7.FriendRequest>>);

  @override
  _i5.Future<void> sendFriendRequest(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#sendFriendRequest, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> acceptRequest(int? friendshipId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptRequest, [friendshipId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> declineRequest(int? friendshipId) =>
      (super.noSuchMethod(
            Invocation.method(#declineRequest, [friendshipId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeFriend(int? friendId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFriend, [friendId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelFriendRequest(int? friendshipId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelFriendRequest, [friendshipId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.FriendshipStatus> getFriendshipStatus(int? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#getFriendshipStatus, [targetUserId]),
            returnValue: _i5.Future<_i2.FriendshipStatus>.value(
              _FakeFriendshipStatus_0(
                this,
                Invocation.method(#getFriendshipStatus, [targetUserId]),
              ),
            ),
          )
          as _i5.Future<_i2.FriendshipStatus>);

  @override
  _i5.Future<List<_i8.UserSearchResult>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i5.Future<List<_i8.UserSearchResult>>.value(
              <_i8.UserSearchResult>[],
            ),
          )
          as _i5.Future<List<_i8.UserSearchResult>>);

  @override
  _i5.Future<_i3.PublicProfile> getPublicProfile(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicProfile, [userId]),
            returnValue: _i5.Future<_i3.PublicProfile>.value(
              _FakePublicProfile_1(
                this,
                Invocation.method(#getPublicProfile, [userId]),
              ),
            ),
          )
          as _i5.Future<_i3.PublicProfile>);
}
