// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/providers/goals_provider_session_ownership_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:go_hard_app/core/services/connectivity_service.dart' as _i6;
import 'package:go_hard_app/data/models/goal.dart' as _i2;
import 'package:go_hard_app/data/models/goal_progress.dart' as _i3;
import 'package:go_hard_app/data/repositories/goals_repository.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGoal_0 extends _i1.SmartFake implements _i2.Goal {
  _FakeGoal_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoalProgress_1 extends _i1.SmartFake implements _i3.GoalProgress {
  _FakeGoalProgress_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GoalsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalsRepository extends _i1.Mock implements _i4.GoalsRepository {
  MockGoalsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Goal>> getGoals({bool? isActive}) =>
      (super.noSuchMethod(
            Invocation.method(#getGoals, [], {#isActive: isActive}),
            returnValue: _i5.Future<List<_i2.Goal>>.value(<_i2.Goal>[]),
          )
          as _i5.Future<List<_i2.Goal>>);

  @override
  _i5.Future<_i2.Goal> getGoalById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalById, [id]),
            returnValue: _i5.Future<_i2.Goal>.value(
              _FakeGoal_0(this, Invocation.method(#getGoalById, [id])),
            ),
          )
          as _i5.Future<_i2.Goal>);

  @override
  _i5.Future<_i2.Goal> createGoal(_i2.Goal? goal) =>
      (super.noSuchMethod(
            Invocation.method(#createGoal, [goal]),
            returnValue: _i5.Future<_i2.Goal>.value(
              _FakeGoal_0(this, Invocation.method(#createGoal, [goal])),
            ),
          )
          as _i5.Future<_i2.Goal>);

  @override
  _i5.Future<void> updateGoal(int? id, _i2.Goal? goal) =>
      (super.noSuchMethod(
            Invocation.method(#updateGoal, [id, goal]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> getDeletionImpact(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletionImpact, [id]),
            returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i5.Future<Map<String, int>>);

  @override
  _i5.Future<void> deleteGoal(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGoal, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> completeGoal(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeGoal, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.GoalProgress> addProgress(
    int? goalId,
    _i3.GoalProgress? progress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addProgress, [goalId, progress]),
            returnValue: _i5.Future<_i3.GoalProgress>.value(
              _FakeGoalProgress_1(
                this,
                Invocation.method(#addProgress, [goalId, progress]),
              ),
            ),
          )
          as _i5.Future<_i3.GoalProgress>);

  @override
  _i5.Future<List<_i3.GoalProgress>> getProgressHistory(int? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressHistory, [goalId]),
            returnValue: _i5.Future<List<_i3.GoalProgress>>.value(
              <_i3.GoalProgress>[],
            ),
          )
          as _i5.Future<List<_i3.GoalProgress>>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i6.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  _i5.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> waitForConnection({
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForConnection, [], {#timeout: timeout}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
