// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/providers/log_sets_provider_session_cleanup_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:go_hard_app/data/models/exercise_set.dart' as _i3;
import 'package:go_hard_app/data/models/exercise_template.dart' as _i2;
import 'package:go_hard_app/data/repositories/exercise_repository.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExerciseTemplate_0 extends _i1.SmartFake
    implements _i2.ExerciseTemplate {
  _FakeExerciseTemplate_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExerciseSet_1 extends _i1.SmartFake implements _i3.ExerciseSet {
  _FakeExerciseSet_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock
    implements _i4.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.ExerciseTemplate>> getExerciseTemplates({
    String? category,
    String? muscleGroup,
    bool? isCustom,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseTemplates, [], {
              #category: category,
              #muscleGroup: muscleGroup,
              #isCustom: isCustom,
            }),
            returnValue: _i5.Future<List<_i2.ExerciseTemplate>>.value(
              <_i2.ExerciseTemplate>[],
            ),
          )
          as _i5.Future<List<_i2.ExerciseTemplate>>);

  @override
  _i5.Future<_i2.ExerciseTemplate> getExerciseTemplate(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseTemplate, [id]),
            returnValue: _i5.Future<_i2.ExerciseTemplate>.value(
              _FakeExerciseTemplate_0(
                this,
                Invocation.method(#getExerciseTemplate, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.ExerciseTemplate>);

  @override
  _i5.Future<List<String>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<List<String>> getMuscleGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getMuscleGroups, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<List<_i3.ExerciseSet>> getExerciseSets(int? exerciseId) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseSets, [exerciseId]),
            returnValue: _i5.Future<List<_i3.ExerciseSet>>.value(
              <_i3.ExerciseSet>[],
            ),
          )
          as _i5.Future<List<_i3.ExerciseSet>>);

  @override
  _i5.Future<_i3.ExerciseSet> createExerciseSet(_i3.ExerciseSet? exerciseSet) =>
      (super.noSuchMethod(
            Invocation.method(#createExerciseSet, [exerciseSet]),
            returnValue: _i5.Future<_i3.ExerciseSet>.value(
              _FakeExerciseSet_1(
                this,
                Invocation.method(#createExerciseSet, [exerciseSet]),
              ),
            ),
          )
          as _i5.Future<_i3.ExerciseSet>);

  @override
  _i5.Future<_i3.ExerciseSet> updateExerciseSet(
    int? id,
    _i3.ExerciseSet? exerciseSet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateExerciseSet, [id, exerciseSet]),
            returnValue: _i5.Future<_i3.ExerciseSet>.value(
              _FakeExerciseSet_1(
                this,
                Invocation.method(#updateExerciseSet, [id, exerciseSet]),
              ),
            ),
          )
          as _i5.Future<_i3.ExerciseSet>);

  @override
  _i5.Future<_i3.ExerciseSet> completeExerciseSet(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeExerciseSet, [id]),
            returnValue: _i5.Future<_i3.ExerciseSet>.value(
              _FakeExerciseSet_1(
                this,
                Invocation.method(#completeExerciseSet, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.ExerciseSet>);

  @override
  _i5.Future<bool> deleteExerciseSet(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExerciseSet, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
