// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/providers/messages_provider_session_ownership_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:go_hard_app/data/models/direct_message.dart' as _i2;
import 'package:go_hard_app/data/models/dm_conversation.dart' as _i5;
import 'package:go_hard_app/data/repositories/direct_messages_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDirectMessage_0 extends _i1.SmartFake implements _i2.DirectMessage {
  _FakeDirectMessage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DirectMessagesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDirectMessagesRepository extends _i1.Mock
    implements _i3.DirectMessagesRepository {
  MockDirectMessagesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.DMConversation>> getConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, []),
            returnValue: _i4.Future<List<_i5.DMConversation>>.value(
              <_i5.DMConversation>[],
            ),
          )
          as _i4.Future<List<_i5.DMConversation>>);

  @override
  _i4.Future<List<_i2.DirectMessage>> getMessages(
    int? friendId, {
    int? beforeId,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMessages,
              [friendId],
              {#beforeId: beforeId, #limit: limit},
            ),
            returnValue: _i4.Future<List<_i2.DirectMessage>>.value(
              <_i2.DirectMessage>[],
            ),
          )
          as _i4.Future<List<_i2.DirectMessage>>);

  @override
  _i4.Future<_i2.DirectMessage> sendMessage(int? friendId, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [friendId, content]),
            returnValue: _i4.Future<_i2.DirectMessage>.value(
              _FakeDirectMessage_0(
                this,
                Invocation.method(#sendMessage, [friendId, content]),
              ),
            ),
          )
          as _i4.Future<_i2.DirectMessage>);

  @override
  _i4.Future<void> markAsRead(int? friendId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [friendId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
