// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/providers/programs_provider_session_ownership_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:go_hard_app/core/services/connectivity_service.dart' as _i6;
import 'package:go_hard_app/data/models/program.dart' as _i2;
import 'package:go_hard_app/data/models/program_workout.dart' as _i3;
import 'package:go_hard_app/data/repositories/programs_repository.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProgram_0 extends _i1.SmartFake implements _i2.Program {
  _FakeProgram_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProgramWorkout_1 extends _i1.SmartFake
    implements _i3.ProgramWorkout {
  _FakeProgramWorkout_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProgramsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgramsRepository extends _i1.Mock
    implements _i4.ProgramsRepository {
  MockProgramsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set afterLocalSessionsReadForTesting(
    _i5.Future<void> Function()? _afterLocalSessionsReadForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterLocalSessionsReadForTesting,
      _afterLocalSessionsReadForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i2.Program>> getPrograms({bool? isActive}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrograms, [], {#isActive: isActive}),
            returnValue: _i5.Future<List<_i2.Program>>.value(<_i2.Program>[]),
          )
          as _i5.Future<List<_i2.Program>>);

  @override
  _i5.Future<_i2.Program> getProgramById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProgramById, [id]),
            returnValue: _i5.Future<_i2.Program>.value(
              _FakeProgram_0(this, Invocation.method(#getProgramById, [id])),
            ),
          )
          as _i5.Future<_i2.Program>);

  @override
  _i5.Future<_i2.Program> createProgram(_i2.Program? program) =>
      (super.noSuchMethod(
            Invocation.method(#createProgram, [program]),
            returnValue: _i5.Future<_i2.Program>.value(
              _FakeProgram_0(
                this,
                Invocation.method(#createProgram, [program]),
              ),
            ),
          )
          as _i5.Future<_i2.Program>);

  @override
  _i5.Future<void> updateProgram(int? id, _i2.Program? program) =>
      (super.noSuchMethod(
            Invocation.method(#updateProgram, [id, program]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> getDeletionImpact(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletionImpact, [id]),
            returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i5.Future<Map<String, int>>);

  @override
  _i5.Future<void> deleteProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProgram, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> completeProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeProgram, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> recalibrateProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#recalibrateProgram, [id]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.Program> advanceProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#advanceProgram, [id]),
            returnValue: _i5.Future<_i2.Program>.value(
              _FakeProgram_0(this, Invocation.method(#advanceProgram, [id])),
            ),
          )
          as _i5.Future<_i2.Program>);

  @override
  _i5.Future<List<_i3.ProgramWorkout>> getWeekWorkouts(
    int? programId,
    int? weekNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWeekWorkouts, [programId, weekNumber]),
            returnValue: _i5.Future<List<_i3.ProgramWorkout>>.value(
              <_i3.ProgramWorkout>[],
            ),
          )
          as _i5.Future<List<_i3.ProgramWorkout>>);

  @override
  _i5.Future<_i3.ProgramWorkout> getTodaysWorkout(int? programId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodaysWorkout, [programId]),
            returnValue: _i5.Future<_i3.ProgramWorkout>.value(
              _FakeProgramWorkout_1(
                this,
                Invocation.method(#getTodaysWorkout, [programId]),
              ),
            ),
          )
          as _i5.Future<_i3.ProgramWorkout>);

  @override
  _i5.Future<_i3.ProgramWorkout> addWorkout(
    int? programId,
    _i3.ProgramWorkout? workout,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addWorkout, [programId, workout]),
            returnValue: _i5.Future<_i3.ProgramWorkout>.value(
              _FakeProgramWorkout_1(
                this,
                Invocation.method(#addWorkout, [programId, workout]),
              ),
            ),
          )
          as _i5.Future<_i3.ProgramWorkout>);

  @override
  _i5.Future<void> updateWorkout(int? workoutId, _i3.ProgramWorkout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkout, [workoutId, workout]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> swapWorkouts(int? workout1Id, int? workout2Id) =>
      (super.noSuchMethod(
            Invocation.method(#swapWorkouts, [workout1Id, workout2Id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> completeWorkout(int? workoutId, {String? notes}) =>
      (super.noSuchMethod(
            Invocation.method(#completeWorkout, [workoutId], {#notes: notes}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteWorkout(int? workoutId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkout, [workoutId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i6.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  _i5.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> waitForConnection({
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForConnection, [], {#timeout: timeout}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
