// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/providers/running_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:go_hard_app/data/models/gps_point.dart' as _i5;
import 'package:go_hard_app/data/models/run_session.dart' as _i2;
import 'package:go_hard_app/data/repositories/running_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRunSession_0 extends _i1.SmartFake implements _i2.RunSession {
  _FakeRunSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RunningRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunningRepository extends _i1.Mock implements _i3.RunningRepository {
  MockRunningRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set beforeWriteTxnForTesting(
    _i4.Future<void> Function()? _beforeWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeWriteTxnForTesting, _beforeWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set insideWriteTxnForTesting(
    _i4.Future<void> Function()? _insideWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#insideWriteTxnForTesting, _insideWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set afterWriteTxnForTesting(
    _i4.Future<void> Function()? _afterWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#afterWriteTxnForTesting, _afterWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set beforeBackgroundHttpDispatchForTesting(
    _i4.Future<void> Function()? _beforeBackgroundHttpDispatchForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeBackgroundHttpDispatchForTesting,
      _beforeBackgroundHttpDispatchForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set afterBackgroundHttpResponseForTesting(
    _i4.Future<void> Function()? _afterBackgroundHttpResponseForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterBackgroundHttpResponseForTesting,
      _afterBackgroundHttpResponseForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set onBackgroundSyncScheduledForTesting(
    void Function(_i4.Future<void>)? _onBackgroundSyncScheduledForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onBackgroundSyncScheduledForTesting,
      _onBackgroundSyncScheduledForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<List<_i2.RunSession>> getRunSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getRunSessions, []),
            returnValue: _i4.Future<List<_i2.RunSession>>.value(
              <_i2.RunSession>[],
            ),
          )
          as _i4.Future<List<_i2.RunSession>>);

  @override
  _i4.Future<List<_i2.RunSession>> getRecentRuns({int? limit = 5}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentRuns, [], {#limit: limit}),
            returnValue: _i4.Future<List<_i2.RunSession>>.value(
              <_i2.RunSession>[],
            ),
          )
          as _i4.Future<List<_i2.RunSession>>);

  @override
  _i4.Future<List<_i2.RunSession>> getThisWeekRuns() =>
      (super.noSuchMethod(
            Invocation.method(#getThisWeekRuns, []),
            returnValue: _i4.Future<List<_i2.RunSession>>.value(
              <_i2.RunSession>[],
            ),
          )
          as _i4.Future<List<_i2.RunSession>>);

  @override
  _i4.Future<_i2.RunSession?> getRunSession(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#getRunSession, [localId]),
            returnValue: _i4.Future<_i2.RunSession?>.value(),
          )
          as _i4.Future<_i2.RunSession?>);

  @override
  _i4.Future<_i2.RunSession> createRunSession() =>
      (super.noSuchMethod(
            Invocation.method(#createRunSession, []),
            returnValue: _i4.Future<_i2.RunSession>.value(
              _FakeRunSession_0(this, Invocation.method(#createRunSession, [])),
            ),
          )
          as _i4.Future<_i2.RunSession>);

  @override
  _i4.Future<_i2.RunSession> startRun(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#startRun, [localId]),
            returnValue: _i4.Future<_i2.RunSession>.value(
              _FakeRunSession_0(this, Invocation.method(#startRun, [localId])),
            ),
          )
          as _i4.Future<_i2.RunSession>);

  @override
  _i4.Future<_i2.RunSession> pauseRun(int? localId, DateTime? pausedAt) =>
      (super.noSuchMethod(
            Invocation.method(#pauseRun, [localId, pausedAt]),
            returnValue: _i4.Future<_i2.RunSession>.value(
              _FakeRunSession_0(
                this,
                Invocation.method(#pauseRun, [localId, pausedAt]),
              ),
            ),
          )
          as _i4.Future<_i2.RunSession>);

  @override
  _i4.Future<_i2.RunSession> resumeRun(int? localId, DateTime? newStartedAt) =>
      (super.noSuchMethod(
            Invocation.method(#resumeRun, [localId, newStartedAt]),
            returnValue: _i4.Future<_i2.RunSession>.value(
              _FakeRunSession_0(
                this,
                Invocation.method(#resumeRun, [localId, newStartedAt]),
              ),
            ),
          )
          as _i4.Future<_i2.RunSession>);

  @override
  _i4.Future<_i2.RunSession> completeRun(
    int? localId, {
    required int? duration,
    required double? distance,
    double? averagePace,
    int? calories,
    List<_i5.GpsPoint>? route,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #completeRun,
              [localId],
              {
                #duration: duration,
                #distance: distance,
                #averagePace: averagePace,
                #calories: calories,
                #route: route,
              },
            ),
            returnValue: _i4.Future<_i2.RunSession>.value(
              _FakeRunSession_0(
                this,
                Invocation.method(
                  #completeRun,
                  [localId],
                  {
                    #duration: duration,
                    #distance: distance,
                    #averagePace: averagePace,
                    #calories: calories,
                    #route: route,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.RunSession>);

  @override
  _i4.Future<void> updateRoute(int? localId, List<_i5.GpsPoint>? route) =>
      (super.noSuchMethod(
            Invocation.method(#updateRoute, [localId, route]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateDistance(int? localId, double? distance) =>
      (super.noSuchMethod(
            Invocation.method(#updateDistance, [localId, distance]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> deleteRun(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRun, [localId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> getWeeklyStats() =>
      (super.noSuchMethod(
            Invocation.method(#getWeeklyStats, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}
