// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/providers/settings_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:go_hard_app/core/services/notification_service.dart' as _i2;
import 'package:go_hard_app/data/models/session.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i2.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> hasPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> ensurePermission() =>
      (super.noSuchMethod(
            Invocation.method(#ensurePermission, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> openSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openSettings, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> scheduleMorningReminder({
    required int? hour,
    required int? minute,
    List<_i4.Session>? todayWorkouts,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleMorningReminder, [], {
              #hour: hour,
              #minute: minute,
              #todayWorkouts: todayWorkouts,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> scheduleEveningReminder({
    required int? hour,
    required int? minute,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleEveningReminder, [], {
              #hour: hour,
              #minute: minute,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> scheduleGoalReminder({
    required int? goalId,
    required String? goalName,
    required String? goalType,
    required String? frequency,
    int? hour = 18,
    int? minute = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleGoalReminder, [], {
              #goalId: goalId,
              #goalName: goalName,
              #goalType: goalType,
              #frequency: frequency,
              #hour: hour,
              #minute: minute,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelGoalReminder(int? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelGoalReminder, [goalId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateGoalReminder({
    required int? goalId,
    required String? goalName,
    required String? goalType,
    required String? frequency,
    int? hour = 18,
    int? minute = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateGoalReminder, [], {
              #goalId: goalId,
              #goalName: goalName,
              #goalType: goalType,
              #frequency: frequency,
              #hour: hour,
              #minute: minute,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateMorningReminder({
    required int? hour,
    required int? minute,
    required List<_i4.Session>? todayWorkouts,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMorningReminder, [], {
              #hour: hour,
              #minute: minute,
              #todayWorkouts: todayWorkouts,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelMorningReminder() =>
      (super.noSuchMethod(
            Invocation.method(#cancelMorningReminder, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelEveningReminder() =>
      (super.noSuchMethod(
            Invocation.method(#cancelEveningReminder, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAll() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> showNutritionGoalNotification({
    required double? consumed,
    required double? goal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showNutritionGoalNotification, [], {
              #consumed: consumed,
              #goal: goal,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelNutritionReminder() =>
      (super.noSuchMethod(
            Invocation.method(#cancelNutritionReminder, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> showTestNotification() =>
      (super.noSuchMethod(
            Invocation.method(#showTestNotification, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
