// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/providers/shared_workout_provider_session_ownership_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:go_hard_app/core/services/connectivity_service.dart' as _i5;
import 'package:go_hard_app/data/models/shared_workout.dart' as _i2;
import 'package:go_hard_app/data/repositories/shared_workout_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedWorkout_0 extends _i1.SmartFake implements _i2.SharedWorkout {
  _FakeSharedWorkout_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SharedWorkoutRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedWorkoutRepository extends _i1.Mock
    implements _i3.SharedWorkoutRepository {
  MockSharedWorkoutRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set beforeWriteTxnForTesting(
    _i4.Future<void> Function()? _beforeWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeWriteTxnForTesting, _beforeWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set insideWriteTxnForTesting(
    _i4.Future<void> Function()? _insideWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#insideWriteTxnForTesting, _insideWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set afterWriteTxnForTesting(
    _i4.Future<void> Function()? _afterWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#afterWriteTxnForTesting, _afterWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set beforeBackgroundHttpDispatchForTesting(
    _i4.Future<void> Function()? _beforeBackgroundHttpDispatchForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeBackgroundHttpDispatchForTesting,
      _beforeBackgroundHttpDispatchForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set afterBackgroundHttpResponseForTesting(
    _i4.Future<void> Function()? _afterBackgroundHttpResponseForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterBackgroundHttpResponseForTesting,
      _afterBackgroundHttpResponseForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set afterForegroundHttpResponseForTesting(
    _i4.Future<void> Function()? _afterForegroundHttpResponseForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterForegroundHttpResponseForTesting,
      _afterForegroundHttpResponseForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set onBackgroundSyncScheduledForTesting(
    void Function(_i4.Future<void>)? _onBackgroundSyncScheduledForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onBackgroundSyncScheduledForTesting,
      _onBackgroundSyncScheduledForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<List<_i2.SharedWorkout>> getSharedWorkouts({
    String? category,
    String? difficulty,
    bool? friendsOnly = true,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSharedWorkouts, [], {
              #category: category,
              #difficulty: difficulty,
              #friendsOnly: friendsOnly,
              #limit: limit,
            }),
            returnValue: _i4.Future<List<_i2.SharedWorkout>>.value(
              <_i2.SharedWorkout>[],
            ),
          )
          as _i4.Future<List<_i2.SharedWorkout>>);

  @override
  _i4.Future<List<_i2.SharedWorkout>> getSharedWorkoutsByUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getSharedWorkoutsByUser, [userId]),
            returnValue: _i4.Future<List<_i2.SharedWorkout>>.value(
              <_i2.SharedWorkout>[],
            ),
          )
          as _i4.Future<List<_i2.SharedWorkout>>);

  @override
  _i4.Future<List<_i2.SharedWorkout>> getMySharedWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getMySharedWorkouts, []),
            returnValue: _i4.Future<List<_i2.SharedWorkout>>.value(
              <_i2.SharedWorkout>[],
            ),
          )
          as _i4.Future<List<_i2.SharedWorkout>>);

  @override
  _i4.Future<_i2.SharedWorkout> shareWorkout({
    required int? originalId,
    required String? type,
    required String? workoutName,
    String? description,
    required String? exercisesJson,
    required int? duration,
    required String? category,
    String? difficulty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shareWorkout, [], {
              #originalId: originalId,
              #type: type,
              #workoutName: workoutName,
              #description: description,
              #exercisesJson: exercisesJson,
              #duration: duration,
              #category: category,
              #difficulty: difficulty,
            }),
            returnValue: _i4.Future<_i2.SharedWorkout>.value(
              _FakeSharedWorkout_0(
                this,
                Invocation.method(#shareWorkout, [], {
                  #originalId: originalId,
                  #type: type,
                  #workoutName: workoutName,
                  #description: description,
                  #exercisesJson: exercisesJson,
                  #duration: duration,
                  #category: category,
                  #difficulty: difficulty,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.SharedWorkout>);

  @override
  _i4.Future<void> toggleLike(int? sharedWorkoutId, bool? isLiked) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [sharedWorkoutId, isLiked]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleSave(int? sharedWorkoutId, bool? isSaved) =>
      (super.noSuchMethod(
            Invocation.method(#toggleSave, [sharedWorkoutId, isSaved]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.SharedWorkout>> getSavedWorkouts() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedWorkouts, []),
            returnValue: _i4.Future<List<_i2.SharedWorkout>>.value(
              <_i2.SharedWorkout>[],
            ),
          )
          as _i4.Future<List<_i2.SharedWorkout>>);

  @override
  _i4.Future<void> deleteSharedWorkout(int? sharedWorkoutId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSharedWorkout, [sharedWorkoutId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i5.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  _i4.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> waitForConnection({
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForConnection, [], {#timeout: timeout}),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
