// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/core/services/sync_service_scheduling_ownership_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;
import 'dart:ui' as _i9;

import 'package:dio/dio.dart' as _i4;
import 'package:go_hard_app/core/services/connectivity_service.dart' as _i8;
import 'package:go_hard_app/data/services/api_service.dart' as _i3;
import 'package:go_hard_app/data/services/auth_service.dart' as _i7;
import 'package:go_hard_app/data/services/session_request_context.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onUnauthorized(void Function()? _onUnauthorized) => super.noSuchMethod(
    Invocation.setter(#onUnauthorized, _onUnauthorized),
    returnValueForMissingStub: null,
  );

  @override
  set beforeDispatchEpochCheckForTesting(
    _i2.Future<void> Function()? _beforeDispatchEpochCheckForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeDispatchEpochCheckForTesting,
      _beforeDispatchEpochCheckForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set testHttpClientAdapter(_i4.HttpClientAdapter? adapter) =>
      super.noSuchMethod(
        Invocation.setter(#testHttpClientAdapter, adapter),
        returnValueForMissingStub: null,
      );

  @override
  void resetUnauthorizedFlag() => super.noSuchMethod(
    Invocation.method(#resetUnauthorizedFlag, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleResponseError(_i4.DioException? error) => super.noSuchMethod(
    Invocation.method(#handleResponseError, [error]),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Future<T> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i5.SessionRequestContext? sessionContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #queryParameters: queryParameters,
                #sessionContext: sessionContext,
              },
            ),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #get,
                      [path],
                      {
                        #queryParameters: queryParameters,
                        #sessionContext: sessionContext,
                      },
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #get,
                    [path],
                    {
                      #queryParameters: queryParameters,
                      #sessionContext: sessionContext,
                    },
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> post<T>(
    String? path, {
    dynamic data,
    _i5.SessionRequestContext? sessionContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {#data: data, #sessionContext: sessionContext},
            ),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #post,
                      [path],
                      {#data: data, #sessionContext: sessionContext},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #post,
                    [path],
                    {#data: data, #sessionContext: sessionContext},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T> put<T>(
    String? path, {
    dynamic data,
    _i5.SessionRequestContext? sessionContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {#data: data, #sessionContext: sessionContext},
            ),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #put,
                      [path],
                      {#data: data, #sessionContext: sessionContext},
                    ),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(
                    #put,
                    [path],
                    {#data: data, #sessionContext: sessionContext},
                  ),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<T?> patch<T>(
    String? path, {
    dynamic data,
    _i5.SessionRequestContext? sessionContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {#data: data, #sessionContext: sessionContext},
            ),
            returnValue: _i2.Future<T?>.value(),
          )
          as _i2.Future<T?>);

  @override
  _i2.Future<bool> delete(
    String? path, {
    dynamic data,
    _i5.SessionRequestContext? sessionContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {#data: data, #sessionContext: sessionContext},
            ),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<void> saveToken({
    required String? token,
    required int? userId,
    required String? name,
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [], {
              #token: token,
              #userId: userId,
              #name: name,
              #email: email,
            }),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i2.Future<String?>.value(),
          )
          as _i2.Future<String?>);

  @override
  _i2.Future<int?> getUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getUserId, []),
            returnValue: _i2.Future<int?>.value(),
          )
          as _i2.Future<int?>);

  @override
  _i2.Future<String?> getUserName() =>
      (super.noSuchMethod(
            Invocation.method(#getUserName, []),
            returnValue: _i2.Future<String?>.value(),
          )
          as _i2.Future<String?>);

  @override
  _i2.Future<String?> getUserEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getUserEmail, []),
            returnValue: _i2.Future<String?>.value(),
          )
          as _i2.Future<String?>);

  @override
  _i2.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> clearSessionCredentials() =>
      (super.noSuchMethod(
            Invocation.method(#clearSessionCredentials, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> saveThemePreference(String? theme) =>
      (super.noSuchMethod(
            Invocation.method(#saveThemePreference, [theme]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<String?> getThemePreference() =>
      (super.noSuchMethod(
            Invocation.method(#getThemePreference, []),
            returnValue: _i2.Future<String?>.value(),
          )
          as _i2.Future<String?>);

  @override
  _i2.Future<void> saveCachedProfile(String? profileJson) =>
      (super.noSuchMethod(
            Invocation.method(#saveCachedProfile, [profileJson]),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<String?> getCachedProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProfile, []),
            returnValue: _i2.Future<String?>.value(),
          )
          as _i2.Future<String?>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i8.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  _i2.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i2.Stream<bool>.empty(),
          )
          as _i2.Stream<bool>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i2.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<bool> waitForConnection({
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForConnection, [], {#timeout: timeout}),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
