// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/ui/screens/programs/program_workout_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i11;

import 'package:go_hard_app/core/services/connectivity_service.dart' as _i10;
import 'package:go_hard_app/data/models/exercise.dart' as _i5;
import 'package:go_hard_app/data/models/program.dart' as _i2;
import 'package:go_hard_app/data/models/program_workout.dart' as _i3;
import 'package:go_hard_app/data/models/session.dart' as _i4;
import 'package:go_hard_app/data/repositories/programs_repository.dart' as _i6;
import 'package:go_hard_app/data/repositories/session_repository.dart' as _i8;
import 'package:go_hard_app/data/repositories/session_sync_diagnostics.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProgram_0 extends _i1.SmartFake implements _i2.Program {
  _FakeProgram_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProgramWorkout_1 extends _i1.SmartFake
    implements _i3.ProgramWorkout {
  _FakeProgramWorkout_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSession_2 extends _i1.SmartFake implements _i4.Session {
  _FakeSession_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExercise_3 extends _i1.SmartFake implements _i5.Exercise {
  _FakeExercise_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProgramsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgramsRepository extends _i1.Mock
    implements _i6.ProgramsRepository {
  MockProgramsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set afterLocalSessionsReadForTesting(
    _i7.Future<void> Function()? _afterLocalSessionsReadForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterLocalSessionsReadForTesting,
      _afterLocalSessionsReadForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<List<_i2.Program>> getPrograms({bool? isActive}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrograms, [], {#isActive: isActive}),
            returnValue: _i7.Future<List<_i2.Program>>.value(<_i2.Program>[]),
          )
          as _i7.Future<List<_i2.Program>>);

  @override
  _i7.Future<_i2.Program> getProgramById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProgramById, [id]),
            returnValue: _i7.Future<_i2.Program>.value(
              _FakeProgram_0(this, Invocation.method(#getProgramById, [id])),
            ),
          )
          as _i7.Future<_i2.Program>);

  @override
  _i7.Future<_i2.Program> createProgram(_i2.Program? program) =>
      (super.noSuchMethod(
            Invocation.method(#createProgram, [program]),
            returnValue: _i7.Future<_i2.Program>.value(
              _FakeProgram_0(
                this,
                Invocation.method(#createProgram, [program]),
              ),
            ),
          )
          as _i7.Future<_i2.Program>);

  @override
  _i7.Future<void> updateProgram(int? id, _i2.Program? program) =>
      (super.noSuchMethod(
            Invocation.method(#updateProgram, [id, program]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>> getDeletionImpact(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletionImpact, [id]),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> deleteProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProgram, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> completeProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeProgram, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> archiveProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#archiveProgram, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> unarchiveProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#unarchiveProgram, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>> recalibrateProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#recalibrateProgram, [id]),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i2.Program> advanceProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#advanceProgram, [id]),
            returnValue: _i7.Future<_i2.Program>.value(
              _FakeProgram_0(this, Invocation.method(#advanceProgram, [id])),
            ),
          )
          as _i7.Future<_i2.Program>);

  @override
  _i7.Future<List<_i3.ProgramWorkout>> getWeekWorkouts(
    int? programId,
    int? weekNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWeekWorkouts, [programId, weekNumber]),
            returnValue: _i7.Future<List<_i3.ProgramWorkout>>.value(
              <_i3.ProgramWorkout>[],
            ),
          )
          as _i7.Future<List<_i3.ProgramWorkout>>);

  @override
  _i7.Future<_i3.ProgramWorkout> getTodaysWorkout(int? programId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodaysWorkout, [programId]),
            returnValue: _i7.Future<_i3.ProgramWorkout>.value(
              _FakeProgramWorkout_1(
                this,
                Invocation.method(#getTodaysWorkout, [programId]),
              ),
            ),
          )
          as _i7.Future<_i3.ProgramWorkout>);

  @override
  _i7.Future<_i3.ProgramWorkout> addWorkout(
    int? programId,
    _i3.ProgramWorkout? workout,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addWorkout, [programId, workout]),
            returnValue: _i7.Future<_i3.ProgramWorkout>.value(
              _FakeProgramWorkout_1(
                this,
                Invocation.method(#addWorkout, [programId, workout]),
              ),
            ),
          )
          as _i7.Future<_i3.ProgramWorkout>);

  @override
  _i7.Future<void> updateWorkout(int? workoutId, _i3.ProgramWorkout? workout) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkout, [workoutId, workout]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> swapWorkouts(int? workout1Id, int? workout2Id) =>
      (super.noSuchMethod(
            Invocation.method(#swapWorkouts, [workout1Id, workout2Id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> completeWorkout(int? workoutId, {String? notes}) =>
      (super.noSuchMethod(
            Invocation.method(#completeWorkout, [workoutId], {#notes: notes}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteWorkout(int? workoutId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkout, [workoutId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> skipWorkout(int? workoutId) =>
      (super.noSuchMethod(
            Invocation.method(#skipWorkout, [workoutId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> unskipWorkout(int? workoutId) =>
      (super.noSuchMethod(
            Invocation.method(#unskipWorkout, [workoutId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i8.SessionRepository {
  MockSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set operationIdGeneratorForTesting(
    String Function()? _operationIdGeneratorForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #operationIdGeneratorForTesting,
      _operationIdGeneratorForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set beforeWriteTxnForTesting(
    _i7.Future<void> Function()? _beforeWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeWriteTxnForTesting, _beforeWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set insideWriteTxnForTesting(
    _i7.Future<void> Function()? _insideWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#insideWriteTxnForTesting, _insideWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set afterWriteTxnForTesting(
    _i7.Future<void> Function()? _afterWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#afterWriteTxnForTesting, _afterWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set beforeBackgroundHttpDispatchForTesting(
    _i7.Future<void> Function()? _beforeBackgroundHttpDispatchForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeBackgroundHttpDispatchForTesting,
      _beforeBackgroundHttpDispatchForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set afterBackgroundHttpResponseForTesting(
    _i7.Future<void> Function()? _afterBackgroundHttpResponseForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterBackgroundHttpResponseForTesting,
      _afterBackgroundHttpResponseForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set insideBackgroundWriteTxnForTesting(
    _i7.Future<void> Function()? _insideBackgroundWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #insideBackgroundWriteTxnForTesting,
      _insideBackgroundWriteTxnForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set beforeChildDeleteForTesting(
    _i7.Future<void> Function()? _beforeChildDeleteForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeChildDeleteForTesting,
      _beforeChildDeleteForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set onBackgroundSyncScheduledForTesting(
    void Function(_i7.Future<void>)? _onBackgroundSyncScheduledForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onBackgroundSyncScheduledForTesting,
      _onBackgroundSyncScheduledForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<List<_i4.Session>> getSessions({bool? waitForSync = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getSessions, [], {#waitForSync: waitForSync}),
            returnValue: _i7.Future<List<_i4.Session>>.value(<_i4.Session>[]),
          )
          as _i7.Future<List<_i4.Session>>);

  @override
  _i7.Future<List<_i4.Session>> getInProgressSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getInProgressSessions, []),
            returnValue: _i7.Future<List<_i4.Session>>.value(<_i4.Session>[]),
          )
          as _i7.Future<List<_i4.Session>>);

  @override
  _i7.Future<_i4.Session> getSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSession, [id]),
            returnValue: _i7.Future<_i4.Session>.value(
              _FakeSession_2(this, Invocation.method(#getSession, [id])),
            ),
          )
          as _i7.Future<_i4.Session>);

  @override
  _i7.Future<_i4.Session> createSession(_i4.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [session]),
            returnValue: _i7.Future<_i4.Session>.value(
              _FakeSession_2(
                this,
                Invocation.method(#createSession, [session]),
              ),
            ),
          )
          as _i7.Future<_i4.Session>);

  @override
  _i7.Future<_i4.Session> createSessionFromProgramWorkout(
    int? programWorkoutId,
    _i3.ProgramWorkout? programWorkout,
    DateTime? programStartDate,
    int? programId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSessionFromProgramWorkout, [
              programWorkoutId,
              programWorkout,
              programStartDate,
              programId,
            ]),
            returnValue: _i7.Future<_i4.Session>.value(
              _FakeSession_2(
                this,
                Invocation.method(#createSessionFromProgramWorkout, [
                  programWorkoutId,
                  programWorkout,
                  programStartDate,
                  programId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i4.Session>);

  @override
  _i7.Future<_i4.Session> updateSessionStatus(
    int? id,
    String? status, {
    int? duration,
    DateTime? startedAtUtc,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSessionStatus,
              [id, status],
              {#duration: duration, #startedAtUtc: startedAtUtc},
            ),
            returnValue: _i7.Future<_i4.Session>.value(
              _FakeSession_2(
                this,
                Invocation.method(
                  #updateSessionStatus,
                  [id, status],
                  {#duration: duration, #startedAtUtc: startedAtUtc},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.Session>);

  @override
  _i7.Future<void> pauseSession(int? id, DateTime? pausedAt) =>
      (super.noSuchMethod(
            Invocation.method(#pauseSession, [id, pausedAt]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resumeSession(int? id, DateTime? newStartedAt) =>
      (super.noSuchMethod(
            Invocation.method(#resumeSession, [id, newStartedAt]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> archiveSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#archiveSession, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i4.Session> updateSessionName(int? id, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateSessionName, [id, name]),
            returnValue: _i7.Future<_i4.Session>.value(
              _FakeSession_2(
                this,
                Invocation.method(#updateSessionName, [id, name]),
              ),
            ),
          )
          as _i7.Future<_i4.Session>);

  @override
  _i7.Future<void> updateWorkoutDate(int? id, DateTime? newDate) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutDate, [id, newDate]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Stream<List<_i4.Session>> watchSessions(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSessions, [userId]),
            returnValue: _i7.Stream<List<_i4.Session>>.empty(),
          )
          as _i7.Stream<List<_i4.Session>>);

  @override
  _i7.Stream<_i9.SessionSyncSnapshot> watchSessionSyncSnapshot(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSessionSyncSnapshot, [userId]),
            returnValue: _i7.Stream<_i9.SessionSyncSnapshot>.empty(),
          )
          as _i7.Stream<_i9.SessionSyncSnapshot>);

  @override
  _i7.Future<_i5.Exercise> addExerciseToSession(
    int? sessionId,
    int? exerciseTemplateId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addExerciseToSession, [
              sessionId,
              exerciseTemplateId,
            ]),
            returnValue: _i7.Future<_i5.Exercise>.value(
              _FakeExercise_3(
                this,
                Invocation.method(#addExerciseToSession, [
                  sessionId,
                  exerciseTemplateId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i5.Exercise>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i10.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  _i7.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i7.Stream<bool>.empty(),
          )
          as _i7.Stream<bool>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> waitForConnection({
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForConnection, [], {#timeout: timeout}),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
