// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/ui/screens/chat/meal_plan_form_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:go_hard_app/data/models/chat_conversation.dart' as _i10;
import 'package:go_hard_app/data/models/chat_message.dart' as _i11;
import 'package:go_hard_app/data/models/food_item.dart' as _i4;
import 'package:go_hard_app/data/models/food_template.dart' as _i5;
import 'package:go_hard_app/data/models/meal_log.dart' as _i3;
import 'package:go_hard_app/data/models/nutrition_goal.dart' as _i6;
import 'package:go_hard_app/data/models/nutrition_summary.dart' as _i7;
import 'package:go_hard_app/data/repositories/chat_repository.dart' as _i2;
import 'package:go_hard_app/data/repositories/nutrition_repository.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMealPlanPreview_0 extends _i1.SmartFake
    implements _i2.MealPlanPreview {
  _FakeMealPlanPreview_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApplyMealPlanResult_1 extends _i1.SmartFake
    implements _i2.ApplyMealPlanResult {
  _FakeApplyMealPlanResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApplyMealPlanWeekResult_2 extends _i1.SmartFake
    implements _i2.ApplyMealPlanWeekResult {
  _FakeApplyMealPlanWeekResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealLog_3 extends _i1.SmartFake implements _i3.MealLog {
  _FakeMealLog_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFoodItem_4 extends _i1.SmartFake implements _i4.FoodItem {
  _FakeFoodItem_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFoodTemplate_5 extends _i1.SmartFake implements _i5.FoodTemplate {
  _FakeFoodTemplate_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNutritionGoal_6 extends _i1.SmartFake implements _i6.NutritionGoal {
  _FakeNutritionGoal_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNutritionProgress_7 extends _i1.SmartFake
    implements _i7.NutritionProgress {
  _FakeNutritionProgress_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNutritionDashboardData_8 extends _i1.SmartFake
    implements _i8.NutritionDashboardData {
  _FakeNutritionDashboardData_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreakInfo_9 extends _i1.SmartFake implements _i7.StreakInfo {
  _FakeStreakInfo_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i2.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set beforeWriteTxnForTesting(
    _i9.Future<void> Function()? _beforeWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeWriteTxnForTesting, _beforeWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set insideWriteTxnForTesting(
    _i9.Future<void> Function()? _insideWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#insideWriteTxnForTesting, _insideWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set afterWriteTxnForTesting(
    _i9.Future<void> Function()? _afterWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#afterWriteTxnForTesting, _afterWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set beforeBackgroundHttpDispatchForTesting(
    _i9.Future<void> Function()? _beforeBackgroundHttpDispatchForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeBackgroundHttpDispatchForTesting,
      _beforeBackgroundHttpDispatchForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set afterBackgroundHttpResponseForTesting(
    _i9.Future<void> Function()? _afterBackgroundHttpResponseForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterBackgroundHttpResponseForTesting,
      _afterBackgroundHttpResponseForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set afterForegroundHttpResponseForTesting(
    _i9.Future<void> Function()? _afterForegroundHttpResponseForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterForegroundHttpResponseForTesting,
      _afterForegroundHttpResponseForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set onBackgroundSyncScheduledForTesting(
    void Function(_i9.Future<void>)? _onBackgroundSyncScheduledForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onBackgroundSyncScheduledForTesting,
      _onBackgroundSyncScheduledForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<List<_i10.ChatConversation>> getConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, []),
            returnValue: _i9.Future<List<_i10.ChatConversation>>.value(
              <_i10.ChatConversation>[],
            ),
          )
          as _i9.Future<List<_i10.ChatConversation>>);

  @override
  _i9.Future<_i10.ChatConversation?> getConversation(int? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversation, [conversationId]),
            returnValue: _i9.Future<_i10.ChatConversation?>.value(),
          )
          as _i9.Future<_i10.ChatConversation?>);

  @override
  _i9.Future<_i10.ChatConversation?> createConversation({
    required String? title,
    required String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [], {
              #title: title,
              #type: type,
            }),
            returnValue: _i9.Future<_i10.ChatConversation?>.value(),
          )
          as _i9.Future<_i10.ChatConversation?>);

  @override
  _i9.Future<_i11.ChatMessage?> sendMessage({
    required int? conversationId,
    required String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #conversationId: conversationId,
              #message: message,
            }),
            returnValue: _i9.Future<_i11.ChatMessage?>.value(),
          )
          as _i9.Future<_i11.ChatMessage?>);

  @override
  _i9.Future<bool> deleteConversation(int? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [conversationId]),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<_i10.ChatConversation?> generateWorkoutPlan({
    required String? goal,
    required String? experienceLevel,
    required int? daysPerWeek,
    required String? equipment,
    String? limitations,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateWorkoutPlan, [], {
              #goal: goal,
              #experienceLevel: experienceLevel,
              #daysPerWeek: daysPerWeek,
              #equipment: equipment,
              #limitations: limitations,
            }),
            returnValue: _i9.Future<_i10.ChatConversation?>.value(),
          )
          as _i9.Future<_i10.ChatConversation?>);

  @override
  _i9.Future<_i10.ChatConversation?> generateMealPlan({
    required String? dietaryGoal,
    int? targetCalories,
    String? macros,
    String? restrictions,
    String? preferences,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateMealPlan, [], {
              #dietaryGoal: dietaryGoal,
              #targetCalories: targetCalories,
              #macros: macros,
              #restrictions: restrictions,
              #preferences: preferences,
            }),
            returnValue: _i9.Future<_i10.ChatConversation?>.value(),
          )
          as _i9.Future<_i10.ChatConversation?>);

  @override
  _i9.Future<_i10.ChatConversation?> analyzeProgress({
    DateTime? startDate,
    DateTime? endDate,
    String? focusArea,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeProgress, [], {
              #startDate: startDate,
              #endDate: endDate,
              #focusArea: focusArea,
            }),
            returnValue: _i9.Future<_i10.ChatConversation?>.value(),
          )
          as _i9.Future<_i10.ChatConversation?>);

  @override
  _i9.Future<_i2.MealPlanPreview> previewMealPlan(int? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#previewMealPlan, [conversationId]),
            returnValue: _i9.Future<_i2.MealPlanPreview>.value(
              _FakeMealPlanPreview_0(
                this,
                Invocation.method(#previewMealPlan, [conversationId]),
              ),
            ),
          )
          as _i9.Future<_i2.MealPlanPreview>);

  @override
  _i9.Future<_i2.ApplyMealPlanResult> applyMealPlanToToday(
    int? conversationId, {
    int? day = 1,
    DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #applyMealPlanToToday,
              [conversationId],
              {#day: day, #date: date},
            ),
            returnValue: _i9.Future<_i2.ApplyMealPlanResult>.value(
              _FakeApplyMealPlanResult_1(
                this,
                Invocation.method(
                  #applyMealPlanToToday,
                  [conversationId],
                  {#day: day, #date: date},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.ApplyMealPlanResult>);

  @override
  _i9.Future<_i2.ApplyMealPlanWeekResult> applyMealPlanWeek(
    int? conversationId, {
    bool? applyAllDays = false,
    List<int>? days,
    DateTime? startDate,
    bool? overwriteExisting = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #applyMealPlanWeek,
              [conversationId],
              {
                #applyAllDays: applyAllDays,
                #days: days,
                #startDate: startDate,
                #overwriteExisting: overwriteExisting,
              },
            ),
            returnValue: _i9.Future<_i2.ApplyMealPlanWeekResult>.value(
              _FakeApplyMealPlanWeekResult_2(
                this,
                Invocation.method(
                  #applyMealPlanWeek,
                  [conversationId],
                  {
                    #applyAllDays: applyAllDays,
                    #days: days,
                    #startDate: startDate,
                    #overwriteExisting: overwriteExisting,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<_i2.ApplyMealPlanWeekResult>);

  @override
  _i9.Future<Map<String, dynamic>> previewSessionsFromPlan({
    required int? conversationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#previewSessionsFromPlan, [], {
              #conversationId: conversationId,
            }),
            returnValue: _i9.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> createSessionsFromPlan({
    required int? conversationId,
    DateTime? startDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSessionsFromPlan, [], {
              #conversationId: conversationId,
              #startDate: startDate,
            }),
            returnValue: _i9.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> createProgramFromPlan({
    required int? conversationId,
    String? title,
    String? description,
    int? goalId,
    int? totalWeeks,
    int? daysPerWeek,
    DateTime? startDate,
    String? draftRevision,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProgramFromPlan, [], {
              #conversationId: conversationId,
              #title: title,
              #description: description,
              #goalId: goalId,
              #totalWeeks: totalWeeks,
              #daysPerWeek: daysPerWeek,
              #startDate: startDate,
              #draftRevision: draftRevision,
            }),
            returnValue: _i9.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i9.Future<Map<String, dynamic>>);
}

/// A class which mocks [NutritionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNutritionRepository extends _i1.Mock
    implements _i8.NutritionRepository {
  MockNutritionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set beforeWriteTxnForTesting(
    _i9.Future<void> Function()? _beforeWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeWriteTxnForTesting, _beforeWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set insideWriteTxnForTesting(
    _i9.Future<void> Function()? _insideWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#insideWriteTxnForTesting, _insideWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set afterWriteTxnForTesting(
    _i9.Future<void> Function()? _afterWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#afterWriteTxnForTesting, _afterWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set beforeBackgroundHttpDispatchForTesting(
    _i9.Future<void> Function()? _beforeBackgroundHttpDispatchForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeBackgroundHttpDispatchForTesting,
      _beforeBackgroundHttpDispatchForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set afterBackgroundHttpResponseForTesting(
    _i9.Future<void> Function()? _afterBackgroundHttpResponseForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterBackgroundHttpResponseForTesting,
      _afterBackgroundHttpResponseForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set insideBackgroundWriteTxnForTesting(
    _i9.Future<void> Function()? _insideBackgroundWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #insideBackgroundWriteTxnForTesting,
      _insideBackgroundWriteTxnForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<_i3.MealLog> getTodaysMealLog({DateTime? date}) =>
      (super.noSuchMethod(
            Invocation.method(#getTodaysMealLog, [], {#date: date}),
            returnValue: _i9.Future<_i3.MealLog>.value(
              _FakeMealLog_3(
                this,
                Invocation.method(#getTodaysMealLog, [], {#date: date}),
              ),
            ),
          )
          as _i9.Future<_i3.MealLog>);

  @override
  _i9.Future<List<_i3.MealLog>> getMealLogs({
    DateTime? startDate,
    DateTime? endDate,
    int? page = 1,
    int? pageSize = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMealLogs, [], {
              #startDate: startDate,
              #endDate: endDate,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i9.Future<List<_i3.MealLog>>.value(<_i3.MealLog>[]),
          )
          as _i9.Future<List<_i3.MealLog>>);

  @override
  _i9.Future<void> updateWaterIntake(int? mealLogId, double? waterIntake) =>
      (super.noSuchMethod(
            Invocation.method(#updateWaterIntake, [mealLogId, waterIntake]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.FoodItem> quickAddFood({
    required int? mealEntryId,
    required int? foodTemplateId,
    double? quantity = 1.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#quickAddFood, [], {
              #mealEntryId: mealEntryId,
              #foodTemplateId: foodTemplateId,
              #quantity: quantity,
            }),
            returnValue: _i9.Future<_i4.FoodItem>.value(
              _FakeFoodItem_4(
                this,
                Invocation.method(#quickAddFood, [], {
                  #mealEntryId: mealEntryId,
                  #foodTemplateId: foodTemplateId,
                  #quantity: quantity,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.FoodItem>);

  @override
  _i9.Future<void> deleteFoodItem(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFoodItem, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i5.FoodTemplate>> getFoodTemplates({
    String? category,
    bool? isCustom,
    int? page = 1,
    int? pageSize = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodTemplates, [], {
              #category: category,
              #isCustom: isCustom,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i9.Future<List<_i5.FoodTemplate>>.value(
              <_i5.FoodTemplate>[],
            ),
          )
          as _i9.Future<List<_i5.FoodTemplate>>);

  @override
  _i9.Future<List<_i5.FoodTemplate>> searchFoods(
    String? query, {
    String? category,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchFoods,
              [query],
              {#category: category, #limit: limit},
            ),
            returnValue: _i9.Future<List<_i5.FoodTemplate>>.value(
              <_i5.FoodTemplate>[],
            ),
          )
          as _i9.Future<List<_i5.FoodTemplate>>);

  @override
  _i9.Future<List<String>> getFoodCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodCategories, []),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<_i5.FoodTemplate?> getFoodByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodByBarcode, [barcode]),
            returnValue: _i9.Future<_i5.FoodTemplate?>.value(),
          )
          as _i9.Future<_i5.FoodTemplate?>);

  @override
  _i9.Future<_i5.FoodTemplate> createFoodTemplate(_i5.FoodTemplate? template) =>
      (super.noSuchMethod(
            Invocation.method(#createFoodTemplate, [template]),
            returnValue: _i9.Future<_i5.FoodTemplate>.value(
              _FakeFoodTemplate_5(
                this,
                Invocation.method(#createFoodTemplate, [template]),
              ),
            ),
          )
          as _i9.Future<_i5.FoodTemplate>);

  @override
  _i9.Future<_i6.NutritionGoal> getActiveNutritionGoal() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveNutritionGoal, []),
            returnValue: _i9.Future<_i6.NutritionGoal>.value(
              _FakeNutritionGoal_6(
                this,
                Invocation.method(#getActiveNutritionGoal, []),
              ),
            ),
          )
          as _i9.Future<_i6.NutritionGoal>);

  @override
  _i9.Future<_i6.NutritionGoal?> getGoalForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalForDate, [date]),
            returnValue: _i9.Future<_i6.NutritionGoal?>.value(),
          )
          as _i9.Future<_i6.NutritionGoal?>);

  @override
  _i9.Future<Map<DateTime, _i8.NutritionHistoryTarget>> getGoalsForDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalsForDateRange, [start, end]),
            returnValue:
                _i9.Future<Map<DateTime, _i8.NutritionHistoryTarget>>.value(
                  <DateTime, _i8.NutritionHistoryTarget>{},
                ),
          )
          as _i9.Future<Map<DateTime, _i8.NutritionHistoryTarget>>);

  @override
  _i9.Future<void> updateNutritionGoal(int? id, _i6.NutritionGoal? goal) =>
      (super.noSuchMethod(
            Invocation.method(#updateNutritionGoal, [id, goal]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i6.NutritionGoal> createNutritionGoal(_i6.NutritionGoal? goal) =>
      (super.noSuchMethod(
            Invocation.method(#createNutritionGoal, [goal]),
            returnValue: _i9.Future<_i6.NutritionGoal>.value(
              _FakeNutritionGoal_6(
                this,
                Invocation.method(#createNutritionGoal, [goal]),
              ),
            ),
          )
          as _i9.Future<_i6.NutritionGoal>);

  @override
  _i9.Future<_i7.NutritionProgress> getNutritionProgress({DateTime? date}) =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionProgress, [], {#date: date}),
            returnValue: _i9.Future<_i7.NutritionProgress>.value(
              _FakeNutritionProgress_7(
                this,
                Invocation.method(#getNutritionProgress, [], {#date: date}),
              ),
            ),
          )
          as _i9.Future<_i7.NutritionProgress>);

  @override
  _i9.Future<_i8.NutritionDashboardData> getNutritionDashboard({
    DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionDashboard, [], {#date: date}),
            returnValue: _i9.Future<_i8.NutritionDashboardData>.value(
              _FakeNutritionDashboardData_8(
                this,
                Invocation.method(#getNutritionDashboard, [], {#date: date}),
              ),
            ),
          )
          as _i9.Future<_i8.NutritionDashboardData>);

  @override
  _i9.Future<_i7.StreakInfo> getStreak() =>
      (super.noSuchMethod(
            Invocation.method(#getStreak, []),
            returnValue: _i9.Future<_i7.StreakInfo>.value(
              _FakeStreakInfo_9(this, Invocation.method(#getStreak, [])),
            ),
          )
          as _i9.Future<_i7.StreakInfo>);

  @override
  _i9.Future<void> markMealAsConsumed(
    int? entryId, {
    bool? isConsumed = true,
    DateTime? consumedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markMealAsConsumed,
              [entryId],
              {#isConsumed: isConsumed, #consumedAt: consumedAt},
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.MealLog> clearAllFood(int? mealLogId) =>
      (super.noSuchMethod(
            Invocation.method(#clearAllFood, [mealLogId]),
            returnValue: _i9.Future<_i3.MealLog>.value(
              _FakeMealLog_3(
                this,
                Invocation.method(#clearAllFood, [mealLogId]),
              ),
            ),
          )
          as _i9.Future<_i3.MealLog>);

  @override
  _i9.Future<_i4.FoodItem> addFoodItem(_i4.FoodItem? foodItem) =>
      (super.noSuchMethod(
            Invocation.method(#addFoodItem, [foodItem]),
            returnValue: _i9.Future<_i4.FoodItem>.value(
              _FakeFoodItem_4(
                this,
                Invocation.method(#addFoodItem, [foodItem]),
              ),
            ),
          )
          as _i9.Future<_i4.FoodItem>);

  @override
  _i9.Future<void> updateFoodQuantity(int? foodItemId, double? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateFoodQuantity, [foodItemId, quantity]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i8.CalculatedNutrition?> calculateNutritionFromMetrics({
    required String? goalType,
    double? targetWeightChange,
    int? timeframeWeeks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateNutritionFromMetrics, [], {
              #goalType: goalType,
              #targetWeightChange: targetWeightChange,
              #timeframeWeeks: timeframeWeeks,
            }),
            returnValue: _i9.Future<_i8.CalculatedNutrition?>.value(),
          )
          as _i9.Future<_i8.CalculatedNutrition?>);

  @override
  _i9.Future<_i8.CalculatedNutrition?> calculateAndSaveNutrition({
    required String? goalType,
    double? targetWeightChange,
    int? timeframeWeeks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateAndSaveNutrition, [], {
              #goalType: goalType,
              #targetWeightChange: targetWeightChange,
              #timeframeWeeks: timeframeWeeks,
            }),
            returnValue: _i9.Future<_i8.CalculatedNutrition?>.value(),
          )
          as _i9.Future<_i8.CalculatedNutrition?>);

  @override
  _i9.Future<List<_i8.ActivityLevelOption>> getActivityLevels() =>
      (super.noSuchMethod(
            Invocation.method(#getActivityLevels, []),
            returnValue: _i9.Future<List<_i8.ActivityLevelOption>>.value(
              <_i8.ActivityLevelOption>[],
            ),
          )
          as _i9.Future<List<_i8.ActivityLevelOption>>);

  @override
  _i9.Future<List<_i8.FoodAlternative>> getFoodAlternatives({
    required String? foodName,
    required double? calories,
    required double? protein,
    required double? carbohydrates,
    required double? fat,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodAlternatives, [], {
              #foodName: foodName,
              #calories: calories,
              #protein: protein,
              #carbohydrates: carbohydrates,
              #fat: fat,
            }),
            returnValue: _i9.Future<List<_i8.FoodAlternative>>.value(
              <_i8.FoodAlternative>[],
            ),
          )
          as _i9.Future<List<_i8.FoodAlternative>>);
}
