// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/ui/screens/sessions/session_detail_sync_issue_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:go_hard_app/data/models/exercise.dart' as _i3;
import 'package:go_hard_app/data/models/program_workout.dart' as _i6;
import 'package:go_hard_app/data/models/session.dart' as _i2;
import 'package:go_hard_app/data/repositories/session_repository.dart' as _i4;
import 'package:go_hard_app/data/repositories/session_sync_diagnostics.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSession_0 extends _i1.SmartFake implements _i2.Session {
  _FakeSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExercise_1 extends _i1.SmartFake implements _i3.Exercise {
  _FakeExercise_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i4.SessionRepository {
  MockSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set beforeWriteTxnForTesting(
    _i5.Future<void> Function()? _beforeWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeWriteTxnForTesting, _beforeWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set insideWriteTxnForTesting(
    _i5.Future<void> Function()? _insideWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#insideWriteTxnForTesting, _insideWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set afterWriteTxnForTesting(
    _i5.Future<void> Function()? _afterWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#afterWriteTxnForTesting, _afterWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set beforeBackgroundHttpDispatchForTesting(
    _i5.Future<void> Function()? _beforeBackgroundHttpDispatchForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeBackgroundHttpDispatchForTesting,
      _beforeBackgroundHttpDispatchForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set afterBackgroundHttpResponseForTesting(
    _i5.Future<void> Function()? _afterBackgroundHttpResponseForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterBackgroundHttpResponseForTesting,
      _afterBackgroundHttpResponseForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set insideBackgroundWriteTxnForTesting(
    _i5.Future<void> Function()? _insideBackgroundWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #insideBackgroundWriteTxnForTesting,
      _insideBackgroundWriteTxnForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set beforeChildDeleteForTesting(
    _i5.Future<void> Function()? _beforeChildDeleteForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeChildDeleteForTesting,
      _beforeChildDeleteForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set onBackgroundSyncScheduledForTesting(
    void Function(_i5.Future<void>)? _onBackgroundSyncScheduledForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onBackgroundSyncScheduledForTesting,
      _onBackgroundSyncScheduledForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i2.Session>> getSessions({bool? waitForSync = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getSessions, [], {#waitForSync: waitForSync}),
            returnValue: _i5.Future<List<_i2.Session>>.value(<_i2.Session>[]),
          )
          as _i5.Future<List<_i2.Session>>);

  @override
  _i5.Future<List<_i2.Session>> getInProgressSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getInProgressSessions, []),
            returnValue: _i5.Future<List<_i2.Session>>.value(<_i2.Session>[]),
          )
          as _i5.Future<List<_i2.Session>>);

  @override
  _i5.Future<_i2.Session> getSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSession, [id]),
            returnValue: _i5.Future<_i2.Session>.value(
              _FakeSession_0(this, Invocation.method(#getSession, [id])),
            ),
          )
          as _i5.Future<_i2.Session>);

  @override
  _i5.Future<_i2.Session> createSession(_i2.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [session]),
            returnValue: _i5.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#createSession, [session]),
              ),
            ),
          )
          as _i5.Future<_i2.Session>);

  @override
  _i5.Future<_i2.Session> createSessionFromProgramWorkout(
    int? programWorkoutId,
    _i6.ProgramWorkout? programWorkout,
    DateTime? programStartDate,
    int? programId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSessionFromProgramWorkout, [
              programWorkoutId,
              programWorkout,
              programStartDate,
              programId,
            ]),
            returnValue: _i5.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#createSessionFromProgramWorkout, [
                  programWorkoutId,
                  programWorkout,
                  programStartDate,
                  programId,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.Session>);

  @override
  _i5.Future<_i2.Session> updateSessionStatus(
    int? id,
    String? status, {
    int? duration,
    DateTime? startedAtUtc,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSessionStatus,
              [id, status],
              {#duration: duration, #startedAtUtc: startedAtUtc},
            ),
            returnValue: _i5.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(
                  #updateSessionStatus,
                  [id, status],
                  {#duration: duration, #startedAtUtc: startedAtUtc},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Session>);

  @override
  _i5.Future<void> pauseSession(int? id, DateTime? pausedAt) =>
      (super.noSuchMethod(
            Invocation.method(#pauseSession, [id, pausedAt]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resumeSession(int? id, DateTime? newStartedAt) =>
      (super.noSuchMethod(
            Invocation.method(#resumeSession, [id, newStartedAt]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> archiveSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#archiveSession, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.Session> updateSessionName(int? id, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateSessionName, [id, name]),
            returnValue: _i5.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#updateSessionName, [id, name]),
              ),
            ),
          )
          as _i5.Future<_i2.Session>);

  @override
  _i5.Future<void> updateWorkoutDate(int? id, DateTime? newDate) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutDate, [id, newDate]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<List<_i2.Session>> watchSessions(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSessions, [userId]),
            returnValue: _i5.Stream<List<_i2.Session>>.empty(),
          )
          as _i5.Stream<List<_i2.Session>>);

  @override
  _i5.Stream<_i7.SessionSyncSnapshot> watchSessionSyncSnapshot(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSessionSyncSnapshot, [userId]),
            returnValue: _i5.Stream<_i7.SessionSyncSnapshot>.empty(),
          )
          as _i5.Stream<_i7.SessionSyncSnapshot>);

  @override
  _i5.Future<_i3.Exercise> addExerciseToSession(
    int? sessionId,
    int? exerciseTemplateId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addExerciseToSession, [
              sessionId,
              exerciseTemplateId,
            ]),
            returnValue: _i5.Future<_i3.Exercise>.value(
              _FakeExercise_1(
                this,
                Invocation.method(#addExerciseToSession, [
                  sessionId,
                  exerciseTemplateId,
                ]),
              ),
            ),
          )
          as _i5.Future<_i3.Exercise>);
}
