// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/ui/screens/sessions/sessions_screen_navigation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:ui' as _i20;

import 'package:go_hard_app/core/services/connectivity_service.dart' as _i19;
import 'package:go_hard_app/data/models/exercise.dart' as _i3;
import 'package:go_hard_app/data/models/exercise_set.dart' as _i5;
import 'package:go_hard_app/data/models/exercise_template.dart' as _i4;
import 'package:go_hard_app/data/models/food_item.dart' as _i10;
import 'package:go_hard_app/data/models/food_template.dart' as _i11;
import 'package:go_hard_app/data/models/gps_point.dart' as _i23;
import 'package:go_hard_app/data/models/meal_log.dart' as _i9;
import 'package:go_hard_app/data/models/nutrition_goal.dart' as _i12;
import 'package:go_hard_app/data/models/nutrition_summary.dart' as _i13;
import 'package:go_hard_app/data/models/program.dart' as _i6;
import 'package:go_hard_app/data/models/program_workout.dart' as _i7;
import 'package:go_hard_app/data/models/run_session.dart' as _i8;
import 'package:go_hard_app/data/models/session.dart' as _i2;
import 'package:go_hard_app/data/repositories/exercise_repository.dart' as _i18;
import 'package:go_hard_app/data/repositories/nutrition_repository.dart'
    as _i14;
import 'package:go_hard_app/data/repositories/programs_repository.dart' as _i21;
import 'package:go_hard_app/data/repositories/running_repository.dart' as _i22;
import 'package:go_hard_app/data/repositories/session_repository.dart' as _i15;
import 'package:go_hard_app/data/repositories/session_sync_diagnostics.dart'
    as _i17;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSession_0 extends _i1.SmartFake implements _i2.Session {
  _FakeSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExercise_1 extends _i1.SmartFake implements _i3.Exercise {
  _FakeExercise_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExerciseTemplate_2 extends _i1.SmartFake
    implements _i4.ExerciseTemplate {
  _FakeExerciseTemplate_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExerciseSet_3 extends _i1.SmartFake implements _i5.ExerciseSet {
  _FakeExerciseSet_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProgram_4 extends _i1.SmartFake implements _i6.Program {
  _FakeProgram_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProgramWorkout_5 extends _i1.SmartFake
    implements _i7.ProgramWorkout {
  _FakeProgramWorkout_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRunSession_6 extends _i1.SmartFake implements _i8.RunSession {
  _FakeRunSession_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealLog_7 extends _i1.SmartFake implements _i9.MealLog {
  _FakeMealLog_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFoodItem_8 extends _i1.SmartFake implements _i10.FoodItem {
  _FakeFoodItem_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFoodTemplate_9 extends _i1.SmartFake implements _i11.FoodTemplate {
  _FakeFoodTemplate_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNutritionGoal_10 extends _i1.SmartFake
    implements _i12.NutritionGoal {
  _FakeNutritionGoal_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNutritionProgress_11 extends _i1.SmartFake
    implements _i13.NutritionProgress {
  _FakeNutritionProgress_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNutritionDashboardData_12 extends _i1.SmartFake
    implements _i14.NutritionDashboardData {
  _FakeNutritionDashboardData_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreakInfo_13 extends _i1.SmartFake implements _i13.StreakInfo {
  _FakeStreakInfo_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i15.SessionRepository {
  MockSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set beforeWriteTxnForTesting(
    _i16.Future<void> Function()? _beforeWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeWriteTxnForTesting, _beforeWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set insideWriteTxnForTesting(
    _i16.Future<void> Function()? _insideWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#insideWriteTxnForTesting, _insideWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set afterWriteTxnForTesting(
    _i16.Future<void> Function()? _afterWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#afterWriteTxnForTesting, _afterWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set beforeBackgroundHttpDispatchForTesting(
    _i16.Future<void> Function()? _beforeBackgroundHttpDispatchForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeBackgroundHttpDispatchForTesting,
      _beforeBackgroundHttpDispatchForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set afterBackgroundHttpResponseForTesting(
    _i16.Future<void> Function()? _afterBackgroundHttpResponseForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterBackgroundHttpResponseForTesting,
      _afterBackgroundHttpResponseForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set insideBackgroundWriteTxnForTesting(
    _i16.Future<void> Function()? _insideBackgroundWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #insideBackgroundWriteTxnForTesting,
      _insideBackgroundWriteTxnForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set beforeChildDeleteForTesting(
    _i16.Future<void> Function()? _beforeChildDeleteForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeChildDeleteForTesting,
      _beforeChildDeleteForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set onBackgroundSyncScheduledForTesting(
    void Function(_i16.Future<void>)? _onBackgroundSyncScheduledForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onBackgroundSyncScheduledForTesting,
      _onBackgroundSyncScheduledForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<List<_i2.Session>> getSessions({bool? waitForSync = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getSessions, [], {#waitForSync: waitForSync}),
            returnValue: _i16.Future<List<_i2.Session>>.value(<_i2.Session>[]),
          )
          as _i16.Future<List<_i2.Session>>);

  @override
  _i16.Future<List<_i2.Session>> getInProgressSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getInProgressSessions, []),
            returnValue: _i16.Future<List<_i2.Session>>.value(<_i2.Session>[]),
          )
          as _i16.Future<List<_i2.Session>>);

  @override
  _i16.Future<_i2.Session> getSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSession, [id]),
            returnValue: _i16.Future<_i2.Session>.value(
              _FakeSession_0(this, Invocation.method(#getSession, [id])),
            ),
          )
          as _i16.Future<_i2.Session>);

  @override
  _i16.Future<_i2.Session> createSession(_i2.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [session]),
            returnValue: _i16.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#createSession, [session]),
              ),
            ),
          )
          as _i16.Future<_i2.Session>);

  @override
  _i16.Future<_i2.Session> createSessionFromProgramWorkout(
    int? programWorkoutId,
    _i7.ProgramWorkout? programWorkout,
    DateTime? programStartDate,
    int? programId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSessionFromProgramWorkout, [
              programWorkoutId,
              programWorkout,
              programStartDate,
              programId,
            ]),
            returnValue: _i16.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#createSessionFromProgramWorkout, [
                  programWorkoutId,
                  programWorkout,
                  programStartDate,
                  programId,
                ]),
              ),
            ),
          )
          as _i16.Future<_i2.Session>);

  @override
  _i16.Future<_i2.Session> updateSessionStatus(
    int? id,
    String? status, {
    int? duration,
    DateTime? startedAtUtc,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSessionStatus,
              [id, status],
              {#duration: duration, #startedAtUtc: startedAtUtc},
            ),
            returnValue: _i16.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(
                  #updateSessionStatus,
                  [id, status],
                  {#duration: duration, #startedAtUtc: startedAtUtc},
                ),
              ),
            ),
          )
          as _i16.Future<_i2.Session>);

  @override
  _i16.Future<void> pauseSession(int? id, DateTime? pausedAt) =>
      (super.noSuchMethod(
            Invocation.method(#pauseSession, [id, pausedAt]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> resumeSession(int? id, DateTime? newStartedAt) =>
      (super.noSuchMethod(
            Invocation.method(#resumeSession, [id, newStartedAt]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<bool> archiveSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#archiveSession, [id]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> deleteSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [id]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<_i2.Session> updateSessionName(int? id, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateSessionName, [id, name]),
            returnValue: _i16.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#updateSessionName, [id, name]),
              ),
            ),
          )
          as _i16.Future<_i2.Session>);

  @override
  _i16.Future<void> updateWorkoutDate(int? id, DateTime? newDate) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutDate, [id, newDate]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Stream<List<_i2.Session>> watchSessions(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSessions, [userId]),
            returnValue: _i16.Stream<List<_i2.Session>>.empty(),
          )
          as _i16.Stream<List<_i2.Session>>);

  @override
  _i16.Stream<_i17.SessionSyncSnapshot> watchSessionSyncSnapshot(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSessionSyncSnapshot, [userId]),
            returnValue: _i16.Stream<_i17.SessionSyncSnapshot>.empty(),
          )
          as _i16.Stream<_i17.SessionSyncSnapshot>);

  @override
  _i16.Future<_i3.Exercise> addExerciseToSession(
    int? sessionId,
    int? exerciseTemplateId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addExerciseToSession, [
              sessionId,
              exerciseTemplateId,
            ]),
            returnValue: _i16.Future<_i3.Exercise>.value(
              _FakeExercise_1(
                this,
                Invocation.method(#addExerciseToSession, [
                  sessionId,
                  exerciseTemplateId,
                ]),
              ),
            ),
          )
          as _i16.Future<_i3.Exercise>);
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock
    implements _i18.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set beforeWriteTxnForTesting(
    _i16.Future<void> Function()? _beforeWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeWriteTxnForTesting, _beforeWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set insideWriteTxnForTesting(
    _i16.Future<void> Function()? _insideWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#insideWriteTxnForTesting, _insideWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<List<_i4.ExerciseTemplate>> getExerciseTemplates({
    String? category,
    String? muscleGroup,
    bool? isCustom,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseTemplates, [], {
              #category: category,
              #muscleGroup: muscleGroup,
              #isCustom: isCustom,
            }),
            returnValue: _i16.Future<List<_i4.ExerciseTemplate>>.value(
              <_i4.ExerciseTemplate>[],
            ),
          )
          as _i16.Future<List<_i4.ExerciseTemplate>>);

  @override
  _i16.Future<_i4.ExerciseTemplate> getExerciseTemplate(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseTemplate, [id]),
            returnValue: _i16.Future<_i4.ExerciseTemplate>.value(
              _FakeExerciseTemplate_2(
                this,
                Invocation.method(#getExerciseTemplate, [id]),
              ),
            ),
          )
          as _i16.Future<_i4.ExerciseTemplate>);

  @override
  _i16.Future<List<String>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i16.Future<List<String>>.value(<String>[]),
          )
          as _i16.Future<List<String>>);

  @override
  _i16.Future<List<String>> getMuscleGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getMuscleGroups, []),
            returnValue: _i16.Future<List<String>>.value(<String>[]),
          )
          as _i16.Future<List<String>>);

  @override
  _i16.Future<List<_i5.ExerciseSet>> getExerciseSets(int? exerciseId) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseSets, [exerciseId]),
            returnValue: _i16.Future<List<_i5.ExerciseSet>>.value(
              <_i5.ExerciseSet>[],
            ),
          )
          as _i16.Future<List<_i5.ExerciseSet>>);

  @override
  _i16.Future<_i5.ExerciseSet> createExerciseSet(
    _i5.ExerciseSet? exerciseSet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createExerciseSet, [exerciseSet]),
            returnValue: _i16.Future<_i5.ExerciseSet>.value(
              _FakeExerciseSet_3(
                this,
                Invocation.method(#createExerciseSet, [exerciseSet]),
              ),
            ),
          )
          as _i16.Future<_i5.ExerciseSet>);

  @override
  _i16.Future<_i5.ExerciseSet> updateExerciseSet(
    int? id,
    _i5.ExerciseSet? exerciseSet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateExerciseSet, [id, exerciseSet]),
            returnValue: _i16.Future<_i5.ExerciseSet>.value(
              _FakeExerciseSet_3(
                this,
                Invocation.method(#updateExerciseSet, [id, exerciseSet]),
              ),
            ),
          )
          as _i16.Future<_i5.ExerciseSet>);

  @override
  _i16.Future<_i5.ExerciseSet> completeExerciseSet(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeExerciseSet, [id]),
            returnValue: _i16.Future<_i5.ExerciseSet>.value(
              _FakeExerciseSet_3(
                this,
                Invocation.method(#completeExerciseSet, [id]),
              ),
            ),
          )
          as _i16.Future<_i5.ExerciseSet>);

  @override
  _i16.Future<bool> deleteExerciseSet(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExerciseSet, [id]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i19.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  _i16.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i16.Stream<bool>.empty(),
          )
          as _i16.Stream<bool>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i16.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<bool> waitForConnection({
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForConnection, [], {#timeout: timeout}),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i20.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i20.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProgramsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgramsRepository extends _i1.Mock
    implements _i21.ProgramsRepository {
  MockProgramsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set afterLocalSessionsReadForTesting(
    _i16.Future<void> Function()? _afterLocalSessionsReadForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterLocalSessionsReadForTesting,
      _afterLocalSessionsReadForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<List<_i6.Program>> getPrograms({bool? isActive}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrograms, [], {#isActive: isActive}),
            returnValue: _i16.Future<List<_i6.Program>>.value(<_i6.Program>[]),
          )
          as _i16.Future<List<_i6.Program>>);

  @override
  _i16.Future<_i6.Program> getProgramById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProgramById, [id]),
            returnValue: _i16.Future<_i6.Program>.value(
              _FakeProgram_4(this, Invocation.method(#getProgramById, [id])),
            ),
          )
          as _i16.Future<_i6.Program>);

  @override
  _i16.Future<_i6.Program> createProgram(_i6.Program? program) =>
      (super.noSuchMethod(
            Invocation.method(#createProgram, [program]),
            returnValue: _i16.Future<_i6.Program>.value(
              _FakeProgram_4(
                this,
                Invocation.method(#createProgram, [program]),
              ),
            ),
          )
          as _i16.Future<_i6.Program>);

  @override
  _i16.Future<void> updateProgram(int? id, _i6.Program? program) =>
      (super.noSuchMethod(
            Invocation.method(#updateProgram, [id, program]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<Map<String, int>> getDeletionImpact(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletionImpact, [id]),
            returnValue: _i16.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i16.Future<Map<String, int>>);

  @override
  _i16.Future<void> deleteProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProgram, [id]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> completeProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeProgram, [id]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<Map<String, dynamic>> recalibrateProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#recalibrateProgram, [id]),
            returnValue: _i16.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i16.Future<Map<String, dynamic>>);

  @override
  _i16.Future<_i6.Program> advanceProgram(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#advanceProgram, [id]),
            returnValue: _i16.Future<_i6.Program>.value(
              _FakeProgram_4(this, Invocation.method(#advanceProgram, [id])),
            ),
          )
          as _i16.Future<_i6.Program>);

  @override
  _i16.Future<List<_i7.ProgramWorkout>> getWeekWorkouts(
    int? programId,
    int? weekNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWeekWorkouts, [programId, weekNumber]),
            returnValue: _i16.Future<List<_i7.ProgramWorkout>>.value(
              <_i7.ProgramWorkout>[],
            ),
          )
          as _i16.Future<List<_i7.ProgramWorkout>>);

  @override
  _i16.Future<_i7.ProgramWorkout> getTodaysWorkout(int? programId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodaysWorkout, [programId]),
            returnValue: _i16.Future<_i7.ProgramWorkout>.value(
              _FakeProgramWorkout_5(
                this,
                Invocation.method(#getTodaysWorkout, [programId]),
              ),
            ),
          )
          as _i16.Future<_i7.ProgramWorkout>);

  @override
  _i16.Future<_i7.ProgramWorkout> addWorkout(
    int? programId,
    _i7.ProgramWorkout? workout,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addWorkout, [programId, workout]),
            returnValue: _i16.Future<_i7.ProgramWorkout>.value(
              _FakeProgramWorkout_5(
                this,
                Invocation.method(#addWorkout, [programId, workout]),
              ),
            ),
          )
          as _i16.Future<_i7.ProgramWorkout>);

  @override
  _i16.Future<void> updateWorkout(
    int? workoutId,
    _i7.ProgramWorkout? workout,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkout, [workoutId, workout]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> swapWorkouts(int? workout1Id, int? workout2Id) =>
      (super.noSuchMethod(
            Invocation.method(#swapWorkouts, [workout1Id, workout2Id]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> completeWorkout(int? workoutId, {String? notes}) =>
      (super.noSuchMethod(
            Invocation.method(#completeWorkout, [workoutId], {#notes: notes}),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> deleteWorkout(int? workoutId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkout, [workoutId]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}

/// A class which mocks [RunningRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunningRepository extends _i1.Mock implements _i22.RunningRepository {
  MockRunningRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set beforeWriteTxnForTesting(
    _i16.Future<void> Function()? _beforeWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeWriteTxnForTesting, _beforeWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set insideWriteTxnForTesting(
    _i16.Future<void> Function()? _insideWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#insideWriteTxnForTesting, _insideWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set afterWriteTxnForTesting(
    _i16.Future<void> Function()? _afterWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#afterWriteTxnForTesting, _afterWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set beforeBackgroundHttpDispatchForTesting(
    _i16.Future<void> Function()? _beforeBackgroundHttpDispatchForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeBackgroundHttpDispatchForTesting,
      _beforeBackgroundHttpDispatchForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set afterBackgroundHttpResponseForTesting(
    _i16.Future<void> Function()? _afterBackgroundHttpResponseForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterBackgroundHttpResponseForTesting,
      _afterBackgroundHttpResponseForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set onBackgroundSyncScheduledForTesting(
    void Function(_i16.Future<void>)? _onBackgroundSyncScheduledForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onBackgroundSyncScheduledForTesting,
      _onBackgroundSyncScheduledForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<List<_i8.RunSession>> getRunSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getRunSessions, []),
            returnValue: _i16.Future<List<_i8.RunSession>>.value(
              <_i8.RunSession>[],
            ),
          )
          as _i16.Future<List<_i8.RunSession>>);

  @override
  _i16.Future<List<_i8.RunSession>> getRecentRuns({int? limit = 5}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentRuns, [], {#limit: limit}),
            returnValue: _i16.Future<List<_i8.RunSession>>.value(
              <_i8.RunSession>[],
            ),
          )
          as _i16.Future<List<_i8.RunSession>>);

  @override
  _i16.Future<List<_i8.RunSession>> getThisWeekRuns() =>
      (super.noSuchMethod(
            Invocation.method(#getThisWeekRuns, []),
            returnValue: _i16.Future<List<_i8.RunSession>>.value(
              <_i8.RunSession>[],
            ),
          )
          as _i16.Future<List<_i8.RunSession>>);

  @override
  _i16.Future<_i8.RunSession?> getRunSession(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#getRunSession, [localId]),
            returnValue: _i16.Future<_i8.RunSession?>.value(),
          )
          as _i16.Future<_i8.RunSession?>);

  @override
  _i16.Future<_i8.RunSession> createRunSession() =>
      (super.noSuchMethod(
            Invocation.method(#createRunSession, []),
            returnValue: _i16.Future<_i8.RunSession>.value(
              _FakeRunSession_6(this, Invocation.method(#createRunSession, [])),
            ),
          )
          as _i16.Future<_i8.RunSession>);

  @override
  _i16.Future<_i8.RunSession> startRun(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#startRun, [localId]),
            returnValue: _i16.Future<_i8.RunSession>.value(
              _FakeRunSession_6(this, Invocation.method(#startRun, [localId])),
            ),
          )
          as _i16.Future<_i8.RunSession>);

  @override
  _i16.Future<_i8.RunSession> pauseRun(int? localId, DateTime? pausedAt) =>
      (super.noSuchMethod(
            Invocation.method(#pauseRun, [localId, pausedAt]),
            returnValue: _i16.Future<_i8.RunSession>.value(
              _FakeRunSession_6(
                this,
                Invocation.method(#pauseRun, [localId, pausedAt]),
              ),
            ),
          )
          as _i16.Future<_i8.RunSession>);

  @override
  _i16.Future<_i8.RunSession> resumeRun(int? localId, DateTime? newStartedAt) =>
      (super.noSuchMethod(
            Invocation.method(#resumeRun, [localId, newStartedAt]),
            returnValue: _i16.Future<_i8.RunSession>.value(
              _FakeRunSession_6(
                this,
                Invocation.method(#resumeRun, [localId, newStartedAt]),
              ),
            ),
          )
          as _i16.Future<_i8.RunSession>);

  @override
  _i16.Future<_i8.RunSession> completeRun(
    int? localId, {
    required int? duration,
    required double? distance,
    double? averagePace,
    int? calories,
    List<_i23.GpsPoint>? route,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #completeRun,
              [localId],
              {
                #duration: duration,
                #distance: distance,
                #averagePace: averagePace,
                #calories: calories,
                #route: route,
              },
            ),
            returnValue: _i16.Future<_i8.RunSession>.value(
              _FakeRunSession_6(
                this,
                Invocation.method(
                  #completeRun,
                  [localId],
                  {
                    #duration: duration,
                    #distance: distance,
                    #averagePace: averagePace,
                    #calories: calories,
                    #route: route,
                  },
                ),
              ),
            ),
          )
          as _i16.Future<_i8.RunSession>);

  @override
  _i16.Future<void> updateRoute(int? localId, List<_i23.GpsPoint>? route) =>
      (super.noSuchMethod(
            Invocation.method(#updateRoute, [localId, route]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> updateDistance(int? localId, double? distance) =>
      (super.noSuchMethod(
            Invocation.method(#updateDistance, [localId, distance]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<bool> deleteRun(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRun, [localId]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<Map<String, dynamic>> getWeeklyStats() =>
      (super.noSuchMethod(
            Invocation.method(#getWeeklyStats, []),
            returnValue: _i16.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i16.Future<Map<String, dynamic>>);
}

/// A class which mocks [NutritionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNutritionRepository extends _i1.Mock
    implements _i14.NutritionRepository {
  MockNutritionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set beforeWriteTxnForTesting(
    _i16.Future<void> Function()? _beforeWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeWriteTxnForTesting, _beforeWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set insideWriteTxnForTesting(
    _i16.Future<void> Function()? _insideWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#insideWriteTxnForTesting, _insideWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set afterWriteTxnForTesting(
    _i16.Future<void> Function()? _afterWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#afterWriteTxnForTesting, _afterWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set beforeBackgroundHttpDispatchForTesting(
    _i16.Future<void> Function()? _beforeBackgroundHttpDispatchForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeBackgroundHttpDispatchForTesting,
      _beforeBackgroundHttpDispatchForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set afterBackgroundHttpResponseForTesting(
    _i16.Future<void> Function()? _afterBackgroundHttpResponseForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterBackgroundHttpResponseForTesting,
      _afterBackgroundHttpResponseForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set insideBackgroundWriteTxnForTesting(
    _i16.Future<void> Function()? _insideBackgroundWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #insideBackgroundWriteTxnForTesting,
      _insideBackgroundWriteTxnForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<_i9.MealLog> getTodaysMealLog() =>
      (super.noSuchMethod(
            Invocation.method(#getTodaysMealLog, []),
            returnValue: _i16.Future<_i9.MealLog>.value(
              _FakeMealLog_7(this, Invocation.method(#getTodaysMealLog, [])),
            ),
          )
          as _i16.Future<_i9.MealLog>);

  @override
  _i16.Future<List<_i9.MealLog>> getMealLogs({
    DateTime? startDate,
    DateTime? endDate,
    int? page = 1,
    int? pageSize = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMealLogs, [], {
              #startDate: startDate,
              #endDate: endDate,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i16.Future<List<_i9.MealLog>>.value(<_i9.MealLog>[]),
          )
          as _i16.Future<List<_i9.MealLog>>);

  @override
  _i16.Future<void> updateWaterIntake(int? mealLogId, double? waterIntake) =>
      (super.noSuchMethod(
            Invocation.method(#updateWaterIntake, [mealLogId, waterIntake]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<_i10.FoodItem> quickAddFood({
    required int? mealEntryId,
    required int? foodTemplateId,
    double? quantity = 1.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#quickAddFood, [], {
              #mealEntryId: mealEntryId,
              #foodTemplateId: foodTemplateId,
              #quantity: quantity,
            }),
            returnValue: _i16.Future<_i10.FoodItem>.value(
              _FakeFoodItem_8(
                this,
                Invocation.method(#quickAddFood, [], {
                  #mealEntryId: mealEntryId,
                  #foodTemplateId: foodTemplateId,
                  #quantity: quantity,
                }),
              ),
            ),
          )
          as _i16.Future<_i10.FoodItem>);

  @override
  _i16.Future<void> deleteFoodItem(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFoodItem, [id]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<List<_i11.FoodTemplate>> getFoodTemplates({
    String? category,
    bool? isCustom,
    int? page = 1,
    int? pageSize = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodTemplates, [], {
              #category: category,
              #isCustom: isCustom,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i16.Future<List<_i11.FoodTemplate>>.value(
              <_i11.FoodTemplate>[],
            ),
          )
          as _i16.Future<List<_i11.FoodTemplate>>);

  @override
  _i16.Future<List<_i11.FoodTemplate>> searchFoods(
    String? query, {
    String? category,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchFoods,
              [query],
              {#category: category, #limit: limit},
            ),
            returnValue: _i16.Future<List<_i11.FoodTemplate>>.value(
              <_i11.FoodTemplate>[],
            ),
          )
          as _i16.Future<List<_i11.FoodTemplate>>);

  @override
  _i16.Future<List<String>> getFoodCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodCategories, []),
            returnValue: _i16.Future<List<String>>.value(<String>[]),
          )
          as _i16.Future<List<String>>);

  @override
  _i16.Future<_i11.FoodTemplate?> getFoodByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodByBarcode, [barcode]),
            returnValue: _i16.Future<_i11.FoodTemplate?>.value(),
          )
          as _i16.Future<_i11.FoodTemplate?>);

  @override
  _i16.Future<_i11.FoodTemplate> createFoodTemplate(
    _i11.FoodTemplate? template,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createFoodTemplate, [template]),
            returnValue: _i16.Future<_i11.FoodTemplate>.value(
              _FakeFoodTemplate_9(
                this,
                Invocation.method(#createFoodTemplate, [template]),
              ),
            ),
          )
          as _i16.Future<_i11.FoodTemplate>);

  @override
  _i16.Future<_i12.NutritionGoal> getActiveNutritionGoal() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveNutritionGoal, []),
            returnValue: _i16.Future<_i12.NutritionGoal>.value(
              _FakeNutritionGoal_10(
                this,
                Invocation.method(#getActiveNutritionGoal, []),
              ),
            ),
          )
          as _i16.Future<_i12.NutritionGoal>);

  @override
  _i16.Future<void> updateNutritionGoal(int? id, _i12.NutritionGoal? goal) =>
      (super.noSuchMethod(
            Invocation.method(#updateNutritionGoal, [id, goal]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<_i12.NutritionGoal> createNutritionGoal(
    _i12.NutritionGoal? goal,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNutritionGoal, [goal]),
            returnValue: _i16.Future<_i12.NutritionGoal>.value(
              _FakeNutritionGoal_10(
                this,
                Invocation.method(#createNutritionGoal, [goal]),
              ),
            ),
          )
          as _i16.Future<_i12.NutritionGoal>);

  @override
  _i16.Future<_i13.NutritionProgress> getNutritionProgress({DateTime? date}) =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionProgress, [], {#date: date}),
            returnValue: _i16.Future<_i13.NutritionProgress>.value(
              _FakeNutritionProgress_11(
                this,
                Invocation.method(#getNutritionProgress, [], {#date: date}),
              ),
            ),
          )
          as _i16.Future<_i13.NutritionProgress>);

  @override
  _i16.Future<_i14.NutritionDashboardData> getNutritionDashboard({
    DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionDashboard, [], {#date: date}),
            returnValue: _i16.Future<_i14.NutritionDashboardData>.value(
              _FakeNutritionDashboardData_12(
                this,
                Invocation.method(#getNutritionDashboard, [], {#date: date}),
              ),
            ),
          )
          as _i16.Future<_i14.NutritionDashboardData>);

  @override
  _i16.Future<_i13.StreakInfo> getStreak() =>
      (super.noSuchMethod(
            Invocation.method(#getStreak, []),
            returnValue: _i16.Future<_i13.StreakInfo>.value(
              _FakeStreakInfo_13(this, Invocation.method(#getStreak, [])),
            ),
          )
          as _i16.Future<_i13.StreakInfo>);

  @override
  _i16.Future<void> markMealAsConsumed(
    int? entryId, {
    bool? isConsumed = true,
    DateTime? consumedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markMealAsConsumed,
              [entryId],
              {#isConsumed: isConsumed, #consumedAt: consumedAt},
            ),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<_i9.MealLog> clearAllFood(int? mealLogId) =>
      (super.noSuchMethod(
            Invocation.method(#clearAllFood, [mealLogId]),
            returnValue: _i16.Future<_i9.MealLog>.value(
              _FakeMealLog_7(
                this,
                Invocation.method(#clearAllFood, [mealLogId]),
              ),
            ),
          )
          as _i16.Future<_i9.MealLog>);

  @override
  _i16.Future<_i10.FoodItem> addFoodItem(_i10.FoodItem? foodItem) =>
      (super.noSuchMethod(
            Invocation.method(#addFoodItem, [foodItem]),
            returnValue: _i16.Future<_i10.FoodItem>.value(
              _FakeFoodItem_8(
                this,
                Invocation.method(#addFoodItem, [foodItem]),
              ),
            ),
          )
          as _i16.Future<_i10.FoodItem>);

  @override
  _i16.Future<void> updateFoodQuantity(int? foodItemId, double? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateFoodQuantity, [foodItemId, quantity]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<_i14.CalculatedNutrition?> calculateNutritionFromMetrics({
    required String? goalType,
    double? targetWeightChange,
    int? timeframeWeeks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateNutritionFromMetrics, [], {
              #goalType: goalType,
              #targetWeightChange: targetWeightChange,
              #timeframeWeeks: timeframeWeeks,
            }),
            returnValue: _i16.Future<_i14.CalculatedNutrition?>.value(),
          )
          as _i16.Future<_i14.CalculatedNutrition?>);

  @override
  _i16.Future<_i14.CalculatedNutrition?> calculateAndSaveNutrition({
    required String? goalType,
    double? targetWeightChange,
    int? timeframeWeeks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateAndSaveNutrition, [], {
              #goalType: goalType,
              #targetWeightChange: targetWeightChange,
              #timeframeWeeks: timeframeWeeks,
            }),
            returnValue: _i16.Future<_i14.CalculatedNutrition?>.value(),
          )
          as _i16.Future<_i14.CalculatedNutrition?>);

  @override
  _i16.Future<List<_i14.ActivityLevelOption>> getActivityLevels() =>
      (super.noSuchMethod(
            Invocation.method(#getActivityLevels, []),
            returnValue: _i16.Future<List<_i14.ActivityLevelOption>>.value(
              <_i14.ActivityLevelOption>[],
            ),
          )
          as _i16.Future<List<_i14.ActivityLevelOption>>);

  @override
  _i16.Future<List<_i14.FoodAlternative>> getFoodAlternatives({
    required String? foodName,
    required double? calories,
    required double? protein,
    required double? carbohydrates,
    required double? fat,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodAlternatives, [], {
              #foodName: foodName,
              #calories: calories,
              #protein: protein,
              #carbohydrates: carbohydrates,
              #fat: fat,
            }),
            returnValue: _i16.Future<List<_i14.FoodAlternative>>.value(
              <_i14.FoodAlternative>[],
            ),
          )
          as _i16.Future<List<_i14.FoodAlternative>>);
}
