// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/ui/screens/train/train_screen_sync_issues_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i12;

import 'package:go_hard_app/core/services/connectivity_service.dart' as _i11;
import 'package:go_hard_app/data/models/exercise.dart' as _i3;
import 'package:go_hard_app/data/models/exercise_set.dart' as _i5;
import 'package:go_hard_app/data/models/exercise_template.dart' as _i4;
import 'package:go_hard_app/data/models/program_workout.dart' as _i8;
import 'package:go_hard_app/data/models/session.dart' as _i2;
import 'package:go_hard_app/data/repositories/exercise_repository.dart' as _i10;
import 'package:go_hard_app/data/repositories/session_repository.dart' as _i6;
import 'package:go_hard_app/data/repositories/session_sync_diagnostics.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSession_0 extends _i1.SmartFake implements _i2.Session {
  _FakeSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExercise_1 extends _i1.SmartFake implements _i3.Exercise {
  _FakeExercise_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExerciseTemplate_2 extends _i1.SmartFake
    implements _i4.ExerciseTemplate {
  _FakeExerciseTemplate_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExerciseSet_3 extends _i1.SmartFake implements _i5.ExerciseSet {
  _FakeExerciseSet_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepository extends _i1.Mock implements _i6.SessionRepository {
  MockSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set beforeWriteTxnForTesting(
    _i7.Future<void> Function()? _beforeWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeWriteTxnForTesting, _beforeWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set insideWriteTxnForTesting(
    _i7.Future<void> Function()? _insideWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#insideWriteTxnForTesting, _insideWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set afterWriteTxnForTesting(
    _i7.Future<void> Function()? _afterWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#afterWriteTxnForTesting, _afterWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set beforeBackgroundHttpDispatchForTesting(
    _i7.Future<void> Function()? _beforeBackgroundHttpDispatchForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeBackgroundHttpDispatchForTesting,
      _beforeBackgroundHttpDispatchForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set afterBackgroundHttpResponseForTesting(
    _i7.Future<void> Function()? _afterBackgroundHttpResponseForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterBackgroundHttpResponseForTesting,
      _afterBackgroundHttpResponseForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set insideBackgroundWriteTxnForTesting(
    _i7.Future<void> Function()? _insideBackgroundWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #insideBackgroundWriteTxnForTesting,
      _insideBackgroundWriteTxnForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set beforeChildDeleteForTesting(
    _i7.Future<void> Function()? _beforeChildDeleteForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeChildDeleteForTesting,
      _beforeChildDeleteForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set onBackgroundSyncScheduledForTesting(
    void Function(_i7.Future<void>)? _onBackgroundSyncScheduledForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #onBackgroundSyncScheduledForTesting,
      _onBackgroundSyncScheduledForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<List<_i2.Session>> getSessions({bool? waitForSync = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getSessions, [], {#waitForSync: waitForSync}),
            returnValue: _i7.Future<List<_i2.Session>>.value(<_i2.Session>[]),
          )
          as _i7.Future<List<_i2.Session>>);

  @override
  _i7.Future<List<_i2.Session>> getInProgressSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getInProgressSessions, []),
            returnValue: _i7.Future<List<_i2.Session>>.value(<_i2.Session>[]),
          )
          as _i7.Future<List<_i2.Session>>);

  @override
  _i7.Future<_i2.Session> getSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSession, [id]),
            returnValue: _i7.Future<_i2.Session>.value(
              _FakeSession_0(this, Invocation.method(#getSession, [id])),
            ),
          )
          as _i7.Future<_i2.Session>);

  @override
  _i7.Future<_i2.Session> createSession(_i2.Session? session) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [session]),
            returnValue: _i7.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#createSession, [session]),
              ),
            ),
          )
          as _i7.Future<_i2.Session>);

  @override
  _i7.Future<_i2.Session> createSessionFromProgramWorkout(
    int? programWorkoutId,
    _i8.ProgramWorkout? programWorkout,
    DateTime? programStartDate,
    int? programId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSessionFromProgramWorkout, [
              programWorkoutId,
              programWorkout,
              programStartDate,
              programId,
            ]),
            returnValue: _i7.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#createSessionFromProgramWorkout, [
                  programWorkoutId,
                  programWorkout,
                  programStartDate,
                  programId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i2.Session>);

  @override
  _i7.Future<_i2.Session> updateSessionStatus(
    int? id,
    String? status, {
    int? duration,
    DateTime? startedAtUtc,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSessionStatus,
              [id, status],
              {#duration: duration, #startedAtUtc: startedAtUtc},
            ),
            returnValue: _i7.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(
                  #updateSessionStatus,
                  [id, status],
                  {#duration: duration, #startedAtUtc: startedAtUtc},
                ),
              ),
            ),
          )
          as _i7.Future<_i2.Session>);

  @override
  _i7.Future<void> pauseSession(int? id, DateTime? pausedAt) =>
      (super.noSuchMethod(
            Invocation.method(#pauseSession, [id, pausedAt]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resumeSession(int? id, DateTime? newStartedAt) =>
      (super.noSuchMethod(
            Invocation.method(#resumeSession, [id, newStartedAt]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> archiveSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#archiveSession, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteSession(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i2.Session> updateSessionName(int? id, String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateSessionName, [id, name]),
            returnValue: _i7.Future<_i2.Session>.value(
              _FakeSession_0(
                this,
                Invocation.method(#updateSessionName, [id, name]),
              ),
            ),
          )
          as _i7.Future<_i2.Session>);

  @override
  _i7.Future<void> updateWorkoutDate(int? id, DateTime? newDate) =>
      (super.noSuchMethod(
            Invocation.method(#updateWorkoutDate, [id, newDate]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Stream<List<_i2.Session>> watchSessions(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSessions, [userId]),
            returnValue: _i7.Stream<List<_i2.Session>>.empty(),
          )
          as _i7.Stream<List<_i2.Session>>);

  @override
  _i7.Stream<_i9.SessionSyncSnapshot> watchSessionSyncSnapshot(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSessionSyncSnapshot, [userId]),
            returnValue: _i7.Stream<_i9.SessionSyncSnapshot>.empty(),
          )
          as _i7.Stream<_i9.SessionSyncSnapshot>);

  @override
  _i7.Future<_i3.Exercise> addExerciseToSession(
    int? sessionId,
    int? exerciseTemplateId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addExerciseToSession, [
              sessionId,
              exerciseTemplateId,
            ]),
            returnValue: _i7.Future<_i3.Exercise>.value(
              _FakeExercise_1(
                this,
                Invocation.method(#addExerciseToSession, [
                  sessionId,
                  exerciseTemplateId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i3.Exercise>);
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock
    implements _i10.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set beforeWriteTxnForTesting(
    _i7.Future<void> Function()? _beforeWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeWriteTxnForTesting, _beforeWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set insideWriteTxnForTesting(
    _i7.Future<void> Function()? _insideWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#insideWriteTxnForTesting, _insideWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<List<_i4.ExerciseTemplate>> getExerciseTemplates({
    String? category,
    String? muscleGroup,
    bool? isCustom,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseTemplates, [], {
              #category: category,
              #muscleGroup: muscleGroup,
              #isCustom: isCustom,
            }),
            returnValue: _i7.Future<List<_i4.ExerciseTemplate>>.value(
              <_i4.ExerciseTemplate>[],
            ),
          )
          as _i7.Future<List<_i4.ExerciseTemplate>>);

  @override
  _i7.Future<_i4.ExerciseTemplate> getExerciseTemplate(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseTemplate, [id]),
            returnValue: _i7.Future<_i4.ExerciseTemplate>.value(
              _FakeExerciseTemplate_2(
                this,
                Invocation.method(#getExerciseTemplate, [id]),
              ),
            ),
          )
          as _i7.Future<_i4.ExerciseTemplate>);

  @override
  _i7.Future<List<String>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<List<String>> getMuscleGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getMuscleGroups, []),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<List<_i5.ExerciseSet>> getExerciseSets(int? exerciseId) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseSets, [exerciseId]),
            returnValue: _i7.Future<List<_i5.ExerciseSet>>.value(
              <_i5.ExerciseSet>[],
            ),
          )
          as _i7.Future<List<_i5.ExerciseSet>>);

  @override
  _i7.Future<_i5.ExerciseSet> createExerciseSet(_i5.ExerciseSet? exerciseSet) =>
      (super.noSuchMethod(
            Invocation.method(#createExerciseSet, [exerciseSet]),
            returnValue: _i7.Future<_i5.ExerciseSet>.value(
              _FakeExerciseSet_3(
                this,
                Invocation.method(#createExerciseSet, [exerciseSet]),
              ),
            ),
          )
          as _i7.Future<_i5.ExerciseSet>);

  @override
  _i7.Future<_i5.ExerciseSet> updateExerciseSet(
    int? id,
    _i5.ExerciseSet? exerciseSet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateExerciseSet, [id, exerciseSet]),
            returnValue: _i7.Future<_i5.ExerciseSet>.value(
              _FakeExerciseSet_3(
                this,
                Invocation.method(#updateExerciseSet, [id, exerciseSet]),
              ),
            ),
          )
          as _i7.Future<_i5.ExerciseSet>);

  @override
  _i7.Future<_i5.ExerciseSet> completeExerciseSet(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeExerciseSet, [id]),
            returnValue: _i7.Future<_i5.ExerciseSet>.value(
              _FakeExerciseSet_3(
                this,
                Invocation.method(#completeExerciseSet, [id]),
              ),
            ),
          )
          as _i7.Future<_i5.ExerciseSet>);

  @override
  _i7.Future<bool> deleteExerciseSet(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExerciseSet, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i11.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  _i7.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i7.Stream<bool>.empty(),
          )
          as _i7.Stream<bool>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> waitForConnection({
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForConnection, [], {#timeout: timeout}),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
