// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/ui/screens/goals/dialogs/smart_goal_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i15;

import 'package:go_hard_app/core/services/connectivity_service.dart' as _i14;
import 'package:go_hard_app/data/models/body_metric.dart' as _i10;
import 'package:go_hard_app/data/models/food_item.dart' as _i5;
import 'package:go_hard_app/data/models/food_template.dart' as _i6;
import 'package:go_hard_app/data/models/goal.dart' as _i2;
import 'package:go_hard_app/data/models/goal_progress.dart' as _i3;
import 'package:go_hard_app/data/models/meal_log.dart' as _i4;
import 'package:go_hard_app/data/models/nutrition_goal.dart' as _i7;
import 'package:go_hard_app/data/models/nutrition_summary.dart' as _i8;
import 'package:go_hard_app/data/repositories/body_metrics_repository.dart'
    as _i13;
import 'package:go_hard_app/data/repositories/goals_repository.dart' as _i11;
import 'package:go_hard_app/data/repositories/nutrition_repository.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGoal_0 extends _i1.SmartFake implements _i2.Goal {
  _FakeGoal_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoalProgress_1 extends _i1.SmartFake implements _i3.GoalProgress {
  _FakeGoalProgress_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMealLog_2 extends _i1.SmartFake implements _i4.MealLog {
  _FakeMealLog_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFoodItem_3 extends _i1.SmartFake implements _i5.FoodItem {
  _FakeFoodItem_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFoodTemplate_4 extends _i1.SmartFake implements _i6.FoodTemplate {
  _FakeFoodTemplate_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNutritionGoal_5 extends _i1.SmartFake implements _i7.NutritionGoal {
  _FakeNutritionGoal_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNutritionProgress_6 extends _i1.SmartFake
    implements _i8.NutritionProgress {
  _FakeNutritionProgress_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNutritionDashboardData_7 extends _i1.SmartFake
    implements _i9.NutritionDashboardData {
  _FakeNutritionDashboardData_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreakInfo_8 extends _i1.SmartFake implements _i8.StreakInfo {
  _FakeStreakInfo_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBodyMetric_9 extends _i1.SmartFake implements _i10.BodyMetric {
  _FakeBodyMetric_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GoalsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalsRepository extends _i1.Mock implements _i11.GoalsRepository {
  MockGoalsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<_i2.Goal>> getGoals({bool? isActive}) =>
      (super.noSuchMethod(
            Invocation.method(#getGoals, [], {#isActive: isActive}),
            returnValue: _i12.Future<List<_i2.Goal>>.value(<_i2.Goal>[]),
          )
          as _i12.Future<List<_i2.Goal>>);

  @override
  _i12.Future<_i2.Goal> getGoalById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalById, [id]),
            returnValue: _i12.Future<_i2.Goal>.value(
              _FakeGoal_0(this, Invocation.method(#getGoalById, [id])),
            ),
          )
          as _i12.Future<_i2.Goal>);

  @override
  _i12.Future<_i2.Goal> createGoal(_i2.Goal? goal) =>
      (super.noSuchMethod(
            Invocation.method(#createGoal, [goal]),
            returnValue: _i12.Future<_i2.Goal>.value(
              _FakeGoal_0(this, Invocation.method(#createGoal, [goal])),
            ),
          )
          as _i12.Future<_i2.Goal>);

  @override
  _i12.Future<void> updateGoal(int? id, _i2.Goal? goal) =>
      (super.noSuchMethod(
            Invocation.method(#updateGoal, [id, goal]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<Map<String, dynamic>> getDeletionImpact(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDeletionImpact, [id]),
            returnValue: _i12.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i12.Future<Map<String, dynamic>>);

  @override
  _i12.Future<void> deleteGoal(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGoal, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> completeGoal(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeGoal, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> archiveGoal(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#archiveGoal, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> unarchiveGoal(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#unarchiveGoal, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i3.GoalProgress> addProgress(
    int? goalId,
    _i3.GoalProgress? progress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addProgress, [goalId, progress]),
            returnValue: _i12.Future<_i3.GoalProgress>.value(
              _FakeGoalProgress_1(
                this,
                Invocation.method(#addProgress, [goalId, progress]),
              ),
            ),
          )
          as _i12.Future<_i3.GoalProgress>);

  @override
  _i12.Future<List<_i3.GoalProgress>> getProgressHistory(int? goalId) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressHistory, [goalId]),
            returnValue: _i12.Future<List<_i3.GoalProgress>>.value(
              <_i3.GoalProgress>[],
            ),
          )
          as _i12.Future<List<_i3.GoalProgress>>);
}

/// A class which mocks [NutritionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNutritionRepository extends _i1.Mock
    implements _i9.NutritionRepository {
  MockNutritionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set beforeWriteTxnForTesting(
    _i12.Future<void> Function()? _beforeWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#beforeWriteTxnForTesting, _beforeWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set insideWriteTxnForTesting(
    _i12.Future<void> Function()? _insideWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#insideWriteTxnForTesting, _insideWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set afterWriteTxnForTesting(
    _i12.Future<void> Function()? _afterWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(#afterWriteTxnForTesting, _afterWriteTxnForTesting),
    returnValueForMissingStub: null,
  );

  @override
  set beforeBackgroundHttpDispatchForTesting(
    _i12.Future<void> Function()? _beforeBackgroundHttpDispatchForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #beforeBackgroundHttpDispatchForTesting,
      _beforeBackgroundHttpDispatchForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set afterBackgroundHttpResponseForTesting(
    _i12.Future<void> Function()? _afterBackgroundHttpResponseForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #afterBackgroundHttpResponseForTesting,
      _afterBackgroundHttpResponseForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  set insideBackgroundWriteTxnForTesting(
    _i12.Future<void> Function()? _insideBackgroundWriteTxnForTesting,
  ) => super.noSuchMethod(
    Invocation.setter(
      #insideBackgroundWriteTxnForTesting,
      _insideBackgroundWriteTxnForTesting,
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i4.MealLog> getTodaysMealLog({DateTime? date}) =>
      (super.noSuchMethod(
            Invocation.method(#getTodaysMealLog, [], {#date: date}),
            returnValue: _i12.Future<_i4.MealLog>.value(
              _FakeMealLog_2(
                this,
                Invocation.method(#getTodaysMealLog, [], {#date: date}),
              ),
            ),
          )
          as _i12.Future<_i4.MealLog>);

  @override
  _i12.Future<List<_i4.MealLog>> getMealLogs({
    DateTime? startDate,
    DateTime? endDate,
    int? page = 1,
    int? pageSize = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMealLogs, [], {
              #startDate: startDate,
              #endDate: endDate,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i12.Future<List<_i4.MealLog>>.value(<_i4.MealLog>[]),
          )
          as _i12.Future<List<_i4.MealLog>>);

  @override
  _i12.Future<void> updateWaterIntake(int? mealLogId, double? waterIntake) =>
      (super.noSuchMethod(
            Invocation.method(#updateWaterIntake, [mealLogId, waterIntake]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i5.FoodItem> quickAddFood({
    required int? mealEntryId,
    required int? foodTemplateId,
    double? quantity = 1.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#quickAddFood, [], {
              #mealEntryId: mealEntryId,
              #foodTemplateId: foodTemplateId,
              #quantity: quantity,
            }),
            returnValue: _i12.Future<_i5.FoodItem>.value(
              _FakeFoodItem_3(
                this,
                Invocation.method(#quickAddFood, [], {
                  #mealEntryId: mealEntryId,
                  #foodTemplateId: foodTemplateId,
                  #quantity: quantity,
                }),
              ),
            ),
          )
          as _i12.Future<_i5.FoodItem>);

  @override
  _i12.Future<void> deleteFoodItem(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFoodItem, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i6.FoodTemplate>> getFoodTemplates({
    String? category,
    bool? isCustom,
    int? page = 1,
    int? pageSize = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodTemplates, [], {
              #category: category,
              #isCustom: isCustom,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i12.Future<List<_i6.FoodTemplate>>.value(
              <_i6.FoodTemplate>[],
            ),
          )
          as _i12.Future<List<_i6.FoodTemplate>>);

  @override
  _i12.Future<List<_i6.FoodTemplate>> searchFoods(
    String? query, {
    String? category,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchFoods,
              [query],
              {#category: category, #limit: limit},
            ),
            returnValue: _i12.Future<List<_i6.FoodTemplate>>.value(
              <_i6.FoodTemplate>[],
            ),
          )
          as _i12.Future<List<_i6.FoodTemplate>>);

  @override
  _i12.Future<List<String>> getFoodCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodCategories, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<_i6.FoodTemplate?> getFoodByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodByBarcode, [barcode]),
            returnValue: _i12.Future<_i6.FoodTemplate?>.value(),
          )
          as _i12.Future<_i6.FoodTemplate?>);

  @override
  _i12.Future<_i6.FoodTemplate> createFoodTemplate(
    _i6.FoodTemplate? template,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createFoodTemplate, [template]),
            returnValue: _i12.Future<_i6.FoodTemplate>.value(
              _FakeFoodTemplate_4(
                this,
                Invocation.method(#createFoodTemplate, [template]),
              ),
            ),
          )
          as _i12.Future<_i6.FoodTemplate>);

  @override
  _i12.Future<_i7.NutritionGoal> getActiveNutritionGoal() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveNutritionGoal, []),
            returnValue: _i12.Future<_i7.NutritionGoal>.value(
              _FakeNutritionGoal_5(
                this,
                Invocation.method(#getActiveNutritionGoal, []),
              ),
            ),
          )
          as _i12.Future<_i7.NutritionGoal>);

  @override
  _i12.Future<_i7.NutritionGoal?> getGoalForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalForDate, [date]),
            returnValue: _i12.Future<_i7.NutritionGoal?>.value(),
          )
          as _i12.Future<_i7.NutritionGoal?>);

  @override
  _i12.Future<Map<DateTime, _i9.NutritionHistoryTarget>> getGoalsForDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalsForDateRange, [start, end]),
            returnValue:
                _i12.Future<Map<DateTime, _i9.NutritionHistoryTarget>>.value(
                  <DateTime, _i9.NutritionHistoryTarget>{},
                ),
          )
          as _i12.Future<Map<DateTime, _i9.NutritionHistoryTarget>>);

  @override
  _i12.Future<void> updateNutritionGoal(int? id, _i7.NutritionGoal? goal) =>
      (super.noSuchMethod(
            Invocation.method(#updateNutritionGoal, [id, goal]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i7.NutritionGoal> createNutritionGoal(_i7.NutritionGoal? goal) =>
      (super.noSuchMethod(
            Invocation.method(#createNutritionGoal, [goal]),
            returnValue: _i12.Future<_i7.NutritionGoal>.value(
              _FakeNutritionGoal_5(
                this,
                Invocation.method(#createNutritionGoal, [goal]),
              ),
            ),
          )
          as _i12.Future<_i7.NutritionGoal>);

  @override
  _i12.Future<_i8.NutritionProgress> getNutritionProgress({DateTime? date}) =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionProgress, [], {#date: date}),
            returnValue: _i12.Future<_i8.NutritionProgress>.value(
              _FakeNutritionProgress_6(
                this,
                Invocation.method(#getNutritionProgress, [], {#date: date}),
              ),
            ),
          )
          as _i12.Future<_i8.NutritionProgress>);

  @override
  _i12.Future<_i9.NutritionDashboardData> getNutritionDashboard({
    DateTime? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionDashboard, [], {#date: date}),
            returnValue: _i12.Future<_i9.NutritionDashboardData>.value(
              _FakeNutritionDashboardData_7(
                this,
                Invocation.method(#getNutritionDashboard, [], {#date: date}),
              ),
            ),
          )
          as _i12.Future<_i9.NutritionDashboardData>);

  @override
  _i12.Future<_i8.StreakInfo> getStreak() =>
      (super.noSuchMethod(
            Invocation.method(#getStreak, []),
            returnValue: _i12.Future<_i8.StreakInfo>.value(
              _FakeStreakInfo_8(this, Invocation.method(#getStreak, [])),
            ),
          )
          as _i12.Future<_i8.StreakInfo>);

  @override
  _i12.Future<void> markMealAsConsumed(
    int? entryId, {
    bool? isConsumed = true,
    DateTime? consumedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markMealAsConsumed,
              [entryId],
              {#isConsumed: isConsumed, #consumedAt: consumedAt},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i4.MealLog> clearAllFood(int? mealLogId) =>
      (super.noSuchMethod(
            Invocation.method(#clearAllFood, [mealLogId]),
            returnValue: _i12.Future<_i4.MealLog>.value(
              _FakeMealLog_2(
                this,
                Invocation.method(#clearAllFood, [mealLogId]),
              ),
            ),
          )
          as _i12.Future<_i4.MealLog>);

  @override
  _i12.Future<_i5.FoodItem> addFoodItem(_i5.FoodItem? foodItem) =>
      (super.noSuchMethod(
            Invocation.method(#addFoodItem, [foodItem]),
            returnValue: _i12.Future<_i5.FoodItem>.value(
              _FakeFoodItem_3(
                this,
                Invocation.method(#addFoodItem, [foodItem]),
              ),
            ),
          )
          as _i12.Future<_i5.FoodItem>);

  @override
  _i12.Future<void> updateFoodQuantity(int? foodItemId, double? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateFoodQuantity, [foodItemId, quantity]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i9.CalculatedNutrition?> calculateNutritionFromMetrics({
    required String? goalType,
    double? targetWeightChange,
    int? timeframeWeeks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateNutritionFromMetrics, [], {
              #goalType: goalType,
              #targetWeightChange: targetWeightChange,
              #timeframeWeeks: timeframeWeeks,
            }),
            returnValue: _i12.Future<_i9.CalculatedNutrition?>.value(),
          )
          as _i12.Future<_i9.CalculatedNutrition?>);

  @override
  _i12.Future<_i9.CalculatedNutrition?> calculateAndSaveNutrition({
    required String? goalType,
    double? targetWeightChange,
    int? timeframeWeeks,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateAndSaveNutrition, [], {
              #goalType: goalType,
              #targetWeightChange: targetWeightChange,
              #timeframeWeeks: timeframeWeeks,
            }),
            returnValue: _i12.Future<_i9.CalculatedNutrition?>.value(),
          )
          as _i12.Future<_i9.CalculatedNutrition?>);

  @override
  _i12.Future<List<_i9.ActivityLevelOption>> getActivityLevels() =>
      (super.noSuchMethod(
            Invocation.method(#getActivityLevels, []),
            returnValue: _i12.Future<List<_i9.ActivityLevelOption>>.value(
              <_i9.ActivityLevelOption>[],
            ),
          )
          as _i12.Future<List<_i9.ActivityLevelOption>>);

  @override
  _i12.Future<List<_i9.FoodAlternative>> getFoodAlternatives({
    required String? foodName,
    required double? calories,
    required double? protein,
    required double? carbohydrates,
    required double? fat,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodAlternatives, [], {
              #foodName: foodName,
              #calories: calories,
              #protein: protein,
              #carbohydrates: carbohydrates,
              #fat: fat,
            }),
            returnValue: _i12.Future<List<_i9.FoodAlternative>>.value(
              <_i9.FoodAlternative>[],
            ),
          )
          as _i12.Future<List<_i9.FoodAlternative>>);
}

/// A class which mocks [BodyMetricsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBodyMetricsRepository extends _i1.Mock
    implements _i13.BodyMetricsRepository {
  MockBodyMetricsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<_i10.BodyMetric>> getBodyMetrics({int? days = 90}) =>
      (super.noSuchMethod(
            Invocation.method(#getBodyMetrics, [], {#days: days}),
            returnValue: _i12.Future<List<_i10.BodyMetric>>.value(
              <_i10.BodyMetric>[],
            ),
          )
          as _i12.Future<List<_i10.BodyMetric>>);

  @override
  _i12.Future<_i10.BodyMetric?> getLatestMetric() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestMetric, []),
            returnValue: _i12.Future<_i10.BodyMetric?>.value(),
          )
          as _i12.Future<_i10.BodyMetric?>);

  @override
  _i12.Future<_i10.BodyMetric> getBodyMetricById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBodyMetricById, [id]),
            returnValue: _i12.Future<_i10.BodyMetric>.value(
              _FakeBodyMetric_9(
                this,
                Invocation.method(#getBodyMetricById, [id]),
              ),
            ),
          )
          as _i12.Future<_i10.BodyMetric>);

  @override
  _i12.Future<_i10.BodyMetric> createBodyMetric(_i10.BodyMetric? metric) =>
      (super.noSuchMethod(
            Invocation.method(#createBodyMetric, [metric]),
            returnValue: _i12.Future<_i10.BodyMetric>.value(
              _FakeBodyMetric_9(
                this,
                Invocation.method(#createBodyMetric, [metric]),
              ),
            ),
          )
          as _i12.Future<_i10.BodyMetric>);

  @override
  _i12.Future<void> updateBodyMetric(int? id, _i10.BodyMetric? metric) =>
      (super.noSuchMethod(
            Invocation.method(#updateBodyMetric, [id, metric]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteBodyMetric(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBodyMetric, [id]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<Map<String, dynamic>>> getChartData({
    String? metric = r'weight',
    int? days = 90,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChartData, [], {
              #metric: metric,
              #days: days,
            }),
            returnValue: _i12.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i12.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i14.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  _i12.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i12.Stream<bool>.empty(),
          )
          as _i12.Stream<bool>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i12.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> waitForConnection({
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForConnection, [], {#timeout: timeout}),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
