// Mocks generated by Mockito 5.4.4 from annotations
// in go_hard_app/test/ui/screens/auth/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:go_hard_app/providers/auth_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i2.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get password =>
      (super.noSuchMethod(
            Invocation.getter(#password),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#password),
            ),
          )
          as String);

  @override
  String get signupName =>
      (super.noSuchMethod(
            Invocation.getter(#signupName),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#signupName),
            ),
          )
          as String);

  @override
  String get signupEmail =>
      (super.noSuchMethod(
            Invocation.getter(#signupEmail),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#signupEmail),
            ),
          )
          as String);

  @override
  String get signupPassword =>
      (super.noSuchMethod(
            Invocation.getter(#signupPassword),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#signupPassword),
            ),
          )
          as String);

  @override
  String get signupConfirmPassword =>
      (super.noSuchMethod(
            Invocation.getter(#signupConfirmPassword),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#signupConfirmPassword),
            ),
          )
          as String);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  String get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as String);

  @override
  bool get isInitializing =>
      (super.noSuchMethod(
            Invocation.getter(#isInitializing),
            returnValue: false,
          )
          as bool);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setEmail(String? value) => super.noSuchMethod(
    Invocation.method(#setEmail, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setPassword(String? value) => super.noSuchMethod(
    Invocation.method(#setPassword, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setSignupName(String? value) => super.noSuchMethod(
    Invocation.method(#setSignupName, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setSignupEmail(String? value) => super.noSuchMethod(
    Invocation.method(#setSignupEmail, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setSignupPassword(String? value) => super.noSuchMethod(
    Invocation.method(#setSignupPassword, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setSignupConfirmPassword(String? value) => super.noSuchMethod(
    Invocation.method(#setSignupConfirmPassword, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> login() =>
      (super.noSuchMethod(
            Invocation.method(#login, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> signup() =>
      (super.noSuchMethod(
            Invocation.method(#signup, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? message) => super.noSuchMethod(
    Invocation.method(#setError, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void updateEmail(String? value) => super.noSuchMethod(
    Invocation.method(#updateEmail, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updatePassword(String? value) => super.noSuchMethod(
    Invocation.method(#updatePassword, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void updateName(String? value) => super.noSuchMethod(
    Invocation.method(#updateName, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
